var searchData=
[
  ['cache_20functions_0',['Cache Functions',['../group___c_m_s_i_s___core___cache_functions.html',1,'']]],
  ['calculation_1',['SPI CRC Calculation',['../group___s_p_i___c_r_c___calculation.html',1,'']]],
  ['call_20addressing_20mode_2',['I2C General Call Addressing Mode',['../group___i2_c___g_e_n_e_r_a_l___c_a_l_l___a_d_d_r_e_s_s_i_n_g___m_o_d_e.html',1,'']]],
  ['callbacks_3',['IRQ Handler and Callbacks',['../group___i2_c___i_r_q___handler__and___callbacks.html',1,'']]],
  ['callbacks_20functions_4',['Callbacks functions',['../group___t_i_m_ex___exported___functions___group6.html',1,'Extended Callbacks functions'],['../group___t_i_m___exported___functions___group9.html',1,'TIM Callbacks functions']]],
  ['can_20aliased_20defines_20maintained_20for_20legacy_20purpose_5',['HAL CAN Aliased Defines maintained for legacy purpose',['../group___h_a_l___c_a_n___aliased___defines.html',1,'']]],
  ['canberra_6',['Canberra',['../group___canberra.html',1,'']]],
  ['capture_20compare_20channel_20state_7',['TIM Capture/Compare Channel State',['../group___channel___c_c___state.html',1,'']]],
  ['capture_20functions_8',['TIM Input Capture functions',['../group___t_i_m___exported___functions___group4.html',1,'']]],
  ['capture_20polarity_9',['TIM Input Capture Polarity',['../group___t_i_m___input___capture___polarity.html',1,'']]],
  ['capture_20prescaler_10',['TIM Input Capture Prescaler',['../group___t_i_m___input___capture___prescaler.html',1,'']]],
  ['capture_20selection_11',['TIM Input Capture Selection',['../group___t_i_m___input___capture___selection.html',1,'']]],
  ['cascade_20filter_12',['High Precision Q31 Biquad Cascade Filter',['../group___biquad_cascade_d_f1__32x64.html',1,'']]],
  ['cascade_20iir_20filters_20using_20a_20direct_20form_20ii_20transposed_20structure_13',['Biquad Cascade IIR Filters Using a Direct Form II Transposed Structure',['../group___biquad_cascade_d_f2_t.html',1,'']]],
  ['cascade_20iir_20filters_20using_20direct_20form_20i_20structure_14',['Biquad Cascade IIR Filters Using Direct Form I Structure',['../group___biquad_cascade_d_f1.html',1,'']]],
  ['ccx_20dma_20request_20selection_15',['CCx DMA request selection',['../group___t_i_m___c_c___d_m_a___request.html',1,'']]],
  ['cec_20aliased_20defines_20maintained_20for_20legacy_20purpose_16',['HAL CEC Aliased Defines maintained for legacy purpose',['../group___h_a_l___c_e_c___aliased___defines.html',1,'']]],
  ['cfgr_20fields_17',['ADCx CFGR fields',['../group___a_d_c___c_f_g_r__fields.html',1,'']]],
  ['cfgr_20sub_20fields_18',['ADCx CFGR sub fields',['../group___a_d_c___c_f_g_r__fields__2.html',1,'']]],
  ['channel_19',['TIM Channel',['../group___t_i_m___channel.html',1,'']]],
  ['channel_201_202_20or_203_20',['TIM Group Channel 5 and Channel 1, 2 or 3',['../group___t_i_m___group___channel5.html',1,'']]],
  ['channel_205_20and_20channel_201_202_20or_203_21',['TIM Group Channel 5 and Channel 1, 2 or 3',['../group___t_i_m___group___channel5.html',1,'']]],
  ['channel_20number_22',['ADC instance - Channel number',['../group___a_d_c___h_a_l___e_c___c_h_a_n_n_e_l.html',1,'']]],
  ['channel_20polarity_23',['TIM Input Channel polarity',['../group___t_i_m___input___channel___polarity.html',1,'']]],
  ['channel_20sampling_20time_24',['Channel - Sampling time',['../group___a_d_c___h_a_l___e_c___c_h_a_n_n_e_l___s_a_m_p_l_i_n_g_t_i_m_e.html',1,'']]],
  ['channel_20single_20or_20differential_20ending_25',['Channel - Single or differential ending',['../group___a_d_c___h_a_l___e_c___c_h_a_n_n_e_l___s_i_n_g_l_e___d_i_f_f___e_n_d_i_n_g.html',1,'']]],
  ['channel_20state_26',['TIM Capture/Compare Channel State',['../group___channel___c_c___state.html',1,'']]],
  ['charging_27',['PWR battery charging',['../group___p_w_r_ex___v_b_a_t___battery___charging.html',1,'']]],
  ['charging_20resistor_20selection_28',['PWR battery charging resistor selection',['../group___p_w_r_ex___v_b_a_t___battery___charging___selection.html',1,'']]],
  ['chebyshev_29',['Chebyshev',['../group___chebyshev.html',1,'']]],
  ['check_20type_30',['FLASH Option Bytes User SRAM2 Parity Check Type',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m2___p_e.html',1,'']]],
  ['cholesky_20and_20ldlt_20decompositions_31',['Cholesky and LDLT decompositions',['../group___matrix_chol.html',1,'']]],
  ['clarke_20transform_32',['Clarke Transform',['../group__clarke.html',1,'Vector Clarke Transform'],['../group__inv__clarke.html',1,'Vector Inverse Clarke Transform']]],
  ['clear_20flags_33',['UART Interruption Clear Flags',['../group___u_a_r_t___i_t___c_l_e_a_r___flags.html',1,'']]],
  ['clear_20input_20polarity_34',['TIM Clear Input Polarity',['../group___t_i_m___clear_input___polarity.html',1,'']]],
  ['clear_20input_20prescaler_35',['TIM Clear Input Prescaler',['../group___t_i_m___clear_input___prescaler.html',1,'']]],
  ['clear_20input_20source_36',['TIM Clear Input Source',['../group___t_i_m___clear_input___source.html',1,'']]],
  ['clipping_37',['Elementwise clipping',['../group___basic_clip.html',1,'']]],
  ['clock_38',['Wake-Up from STOP Clock',['../group___r_c_c___stop___wake_up_clock.html',1,'']]],
  ['clock_20configuration_39',['RCC RTC Clock Configuration',['../group___r_c_c___r_t_c___clock___configuration.html',1,'']]],
  ['clock_20divider_40',['Clock Divider',['../group___r_c_c___p_l_l_q___clock___divider.html',1,'PLLQ Clock Divider'],['../group___r_c_c___p_l_l_r___clock___divider.html',1,'PLLR Clock Divider']]],
  ['clock_20division_41',['TIM Clock Division',['../group___t_i_m___clock_division.html',1,'']]],
  ['clock_20enable_20disable_42',['Clock Enable Disable',['../group___r_c_c___a_h_b1___peripheral___clock___enable___disable.html',1,'AHB1 Peripheral Clock Enable Disable'],['../group___r_c_c___a_h_b2___peripheral___clock___enable___disable.html',1,'AHB2 Peripheral Clock Enable Disable'],['../group___r_c_c___a_h_b3___clock___enable___disable.html',1,'AHB3 Peripheral Clock Enable Disable'],['../group___r_c_c___a_p_b1___clock___enable___disable.html',1,'APB1 Peripheral Clock Enable Disable'],['../group___r_c_c___a_p_b2___clock___enable___disable.html',1,'APB2 Peripheral Clock Enable Disable']]],
  ['clock_20enabled_20or_20disabled_20status_43',['Clock Enabled or Disabled Status',['../group___r_c_c___a_h_b1___peripheral___clock___enable___disable___status.html',1,'AHB1 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b2___clock___enable___disable___status.html',1,'AHB2 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b3___clock___enable___disable___status.html',1,'AHB3 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_p_b1___clock___enable___disable___status.html',1,'APB1 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_p_b2___clock___enable___disable___status.html',1,'APB2 Peripheral Clock Enabled or Disabled Status']]],
  ['clock_20output_44',['PLL Clock Output',['../group___r_c_c___p_l_l___clock___output.html',1,'']]],
  ['clock_20phase_45',['SPI Clock Phase',['../group___s_p_i___clock___phase.html',1,'']]],
  ['clock_20polarity_46',['Clock Polarity',['../group___s_p_i___clock___polarity.html',1,'SPI Clock Polarity'],['../group___t_i_m___clock___polarity.html',1,'TIM Clock Polarity']]],
  ['clock_20prescaler_47',['Clock Prescaler',['../group___r_c_c___m_c_ox___clock___prescaler.html',1,'MCO1 Clock Prescaler'],['../group___t_i_m___clock___prescaler.html',1,'TIM Clock Prescaler']]],
  ['clock_20range_48',['MSI Clock Range',['../group___r_c_c___m_s_i___clock___range.html',1,'']]],
  ['clock_20selection_49',['Periph Clock Selection',['../group___r_c_c_ex___periph___clock___selection.html',1,'']]],
  ['clock_20sleep_20enable_20disable_50',['Clock Sleep Enable Disable',['../group___r_c_c___a_h_b1___clock___sleep___enable___disable.html',1,'AHB1 Peripheral Clock Sleep Enable Disable'],['../group___r_c_c___a_h_b2___clock___sleep___enable___disable.html',1,'AHB2 Peripheral Clock Sleep Enable Disable'],['../group___r_c_c___a_h_b3___clock___sleep___enable___disable.html',1,'AHB3 Peripheral Clock Sleep Enable Disable'],['../group___r_c_c___a_p_b1___clock___sleep___enable___disable.html',1,'APB1 Peripheral Clock Sleep Enable Disable'],['../group___r_c_c___a_p_b2___clock___sleep___enable___disable.html',1,'APB2 Peripheral Clock Sleep Enable Disable']]],
  ['clock_20sleep_20enabled_20or_20disabled_20status_51',['Clock Sleep Enabled or Disabled Status',['../group___r_c_c___a_h_b1___clock___sleep___enable___disable___status.html',1,'AHB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_h_b2___clock___sleep___enable___disable___status.html',1,'AHB2 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_h_b3___clock___sleep___enable___disable___status.html',1,'AHB3 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b1___clock___sleep___enable___disable___status.html',1,'APB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b2___clock___sleep___enable___disable___status.html',1,'APB2 Peripheral Clock Sleep Enabled or Disabled Status']]],
  ['clock_20source_52',['Clock Source',['../group___r_c_c_ex___a_d_c___clock___source.html',1,'ADC Clock Source'],['../group___r_c_c___a_h_b___clock___source.html',1,'AHB Clock Source'],['../group___r_c_c___a_p_b1___a_p_b2___clock___source.html',1,'APB1 APB2 Clock Source'],['../group___r_c_c_ex___i2_c1___clock___source.html',1,'I2C1 Clock Source'],['../group___r_c_c_ex___i2_c3___clock___source.html',1,'I2C3 Clock Source'],['../group___r_c_c_ex___l_s_c_o___clock___source.html',1,'Low Speed Clock Source'],['../group___r_c_c_ex___l_p_t_i_m1___clock___source.html',1,'LPTIM1 Clock Source'],['../group___r_c_c_ex___l_p_t_i_m2___clock___source.html',1,'LPTIM2 Clock Source'],['../group___r_c_c_ex___l_p_u_a_r_t1___clock___source.html',1,'LPUART1 Clock Source'],['../group___r_c_c___m_c_o1___clock___source.html',1,'MCO1 Clock Source'],['../group___r_c_c___p_l_l___clock___source.html',1,'PLL Clock Source'],['../group___r_c_c_ex___r_n_g___clock___source.html',1,'RNG Clock Source'],['../group___r_c_c___r_t_c___clock___source.html',1,'RTC Clock Source'],['../group___r_c_c___system___clock___source.html',1,'System Clock Source'],['../group___c_o_r_t_e_x___l_l___e_c___c_l_k_s_o_u_r_c_e___h_c_l_k.html',1,'SYSTICK Clock Source'],['../group___t_i_m___clock___source.html',1,'TIM Clock Source'],['../group___r_c_c_ex___u_s_a_r_t1___clock___source.html',1,'USART1 Clock Source'],['../group___r_c_c_ex___u_s_a_r_t2___clock___source.html',1,'USART2 Clock Source']]],
  ['clock_20source_53',['ADC common - Clock source',['../group___a_d_c___h_a_l___e_c___c_o_m_m_o_n___c_l_o_c_k___s_o_u_r_c_e.html',1,'']]],
  ['clock_20source_54',['CORTEX SysTick clock source',['../group___c_o_r_t_e_x___sys_tick__clock__source.html',1,'']]],
  ['clock_20source_20status_55',['System Clock Source Status',['../group___r_c_c___system___clock___source___status.html',1,'']]],
  ['clock_20type_56',['System Clock Type',['../group___r_c_c___system___clock___type.html',1,'']]],
  ['cmsis_57',['CMSIS',['../group___c_m_s_i_s.html',1,'']]],
  ['cmsis_20core_20instruction_20interface_58',['CMSIS Core Instruction Interface',['../group___c_m_s_i_s___core___instruction_interface.html',1,'']]],
  ['cmsis_20core_20register_20access_20functions_59',['CMSIS Core Register Access Functions',['../group___c_m_s_i_s___core___reg_acc_functions.html',1,'']]],
  ['cmsis_20global_20defines_60',['CMSIS Global Defines',['../group___c_m_s_i_s__glob__defs.html',1,'']]],
  ['cmsis_20simd_20intrinsics_61',['CMSIS SIMD Intrinsics',['../group___c_m_s_i_s___s_i_m_d__intrinsics.html',1,'']]],
  ['cmsis_5fdevice_62',['CMSIS_Device',['../group___c_m_s_i_s___device.html',1,'']]],
  ['code_63',['Code',['../group___a_d_c___error___code.html',1,'ADC Error Code'],['../group___d_m_a___error___code.html',1,'DMA Error Code'],['../group___s_p_i___error___code.html',1,'SPI Error Code']]],
  ['code_20definition_64',['UART State Code Definition',['../group___u_a_r_t___state___definition.html',1,'']]],
  ['code_20definition_65',['I2C Error Code definition',['../group___i2_c___error___code__definition.html',1,'']]],
  ['common_20clock_20source_66',['ADC common - Clock source',['../group___a_d_c___h_a_l___e_c___c_o_m_m_o_n___c_l_o_c_k___s_o_u_r_c_e.html',1,'']]],
  ['communications_20time_20out_20value_67',['UART polling-based communications time-out value',['../group___u_a_r_t___time_out___value.html',1,'']]],
  ['commutation_20source_68',['TIM Commutation Source',['../group___t_i_m___commutation___source.html',1,'']]],
  ['comp_20aliased_20defines_20maintained_20for_20legacy_20purpose_69',['HAL COMP Aliased Defines maintained for legacy purpose',['../group___h_a_l___c_o_m_p___aliased___defines.html',1,'']]],
  ['comp_20aliased_20macros_20maintained_20for_20legacy_20purpose_70',['HAL COMP Aliased Macros maintained for legacy purpose',['../group___h_a_l___c_o_m_p___aliased___macros.html',1,'']]],
  ['compare_20and_20pwm_20modes_71',['TIM Output Compare and PWM Modes',['../group___t_i_m___output___compare__and___p_w_m__modes.html',1,'']]],
  ['compare_20channel_20state_72',['TIM Capture/Compare Channel State',['../group___channel___c_c___state.html',1,'']]],
  ['compare_20functions_73',['Compare functions',['../group___t_i_m_ex___exported___functions___group2.html',1,'Extended Timer Complementary Output Compare functions'],['../group___t_i_m___exported___functions___group2.html',1,'TIM Output Compare functions']]],
  ['compare_20idle_20state_74',['Compare Idle State',['../group___t_i_m___output___compare___n___idle___state.html',1,'TIM Complementary Output Compare Idle State'],['../group___t_i_m___output___compare___idle___state.html',1,'TIM Output Compare Idle State']]],
  ['compare_20polarity_75',['Compare Polarity',['../group___t_i_m___output___compare___n___polarity.html',1,'TIM Complementary Output Compare Polarity'],['../group___t_i_m___output___compare___polarity.html',1,'TIM Output Compare Polarity']]],
  ['compare_20state_76',['Compare State',['../group___t_i_m___output___compare___n___state.html',1,'TIM Complementary Output Compare State'],['../group___t_i_m___output___compare___state.html',1,'TIM Output Compare State']]],
  ['compatibility_20purpose_77',['LL FMC Aliased Defines maintained for compatibility purpose',['../group___l_l___f_m_c___aliased___defines.html',1,'']]],
  ['complementary_20one_20pulse_20functions_78',['Extended Timer Complementary One Pulse functions',['../group___t_i_m_ex___exported___functions___group4.html',1,'']]],
  ['complementary_20output_20compare_20functions_79',['Extended Timer Complementary Output Compare functions',['../group___t_i_m_ex___exported___functions___group2.html',1,'']]],
  ['complementary_20output_20compare_20idle_20state_80',['TIM Complementary Output Compare Idle State',['../group___t_i_m___output___compare___n___idle___state.html',1,'']]],
  ['complementary_20output_20compare_20polarity_81',['TIM Complementary Output Compare Polarity',['../group___t_i_m___output___compare___n___polarity.html',1,'']]],
  ['complementary_20output_20compare_20state_82',['TIM Complementary Output Compare State',['../group___t_i_m___output___compare___n___state.html',1,'']]],
  ['complementary_20pwm_20functions_83',['Extended Timer Complementary PWM functions',['../group___t_i_m_ex___exported___functions___group3.html',1,'']]],
  ['complex_20by_20complex_20multiplication_84',['Complex-by-Complex Multiplication',['../group___cmplx_by_cmplx_mult.html',1,'']]],
  ['complex_20by_20real_20multiplication_85',['Complex-by-Real Multiplication',['../group___cmplx_by_real_mult.html',1,'']]],
  ['complex_20conjugate_86',['Complex Conjugate',['../group__cmplx__conj.html',1,'']]],
  ['complex_20dot_20product_87',['Complex Dot Product',['../group__cmplx__dot__prod.html',1,'']]],
  ['complex_20fft_20f16_88',['Complex FFT F16',['../group___complex_f_f_t_f16.html',1,'']]],
  ['complex_20fft_20f32_89',['Complex FFT F32',['../group___complex_f_f_t_f32.html',1,'']]],
  ['complex_20fft_20f64_90',['Complex FFT F64',['../group___complex_f_f_t_f64.html',1,'']]],
  ['complex_20fft_20functions_91',['Complex FFT Functions',['../group___complex_f_f_t.html',1,'']]],
  ['complex_20fft_20functions_92',['Deprecated Complex FFT functions',['../group___complex_f_f_t_deprecated.html',1,'']]],
  ['complex_20fft_20q15_93',['Complex FFT Q15',['../group___complex_f_f_t_q15.html',1,'']]],
  ['complex_20fft_20q31_94',['Complex FFT Q31',['../group___complex_f_f_t_q31.html',1,'']]],
  ['complex_20fft_20tables_95',['Complex FFT Tables',['../group___c_f_f_t___c_i_f_f_t.html',1,'']]],
  ['complex_20magnitude_96',['Complex Magnitude',['../group__cmplx__mag.html',1,'']]],
  ['complex_20magnitude_20squared_97',['Complex Magnitude Squared',['../group__cmplx__mag__squared.html',1,'']]],
  ['complex_20math_20functions_98',['Complex Math Functions',['../group__group_cmplx_math.html',1,'']]],
  ['complex_20matrix_20multiplication_99',['Complex Matrix Multiplication',['../group___cmplx_matrix_mult.html',1,'']]],
  ['complex_20matrix_20transpose_100',['Complex Matrix Transpose',['../group___matrix_complex_trans.html',1,'']]],
  ['complex_20multiplication_101',['Complex-by-Complex Multiplication',['../group___cmplx_by_cmplx_mult.html',1,'']]],
  ['config_102',['Config',['../group___r_c_c___h_s_e___config.html',1,'HSE Config'],['../group___r_c_c___h_s_i___config.html',1,'HSI Config'],['../group___r_c_c___h_s_i48___config.html',1,'HSI48 Config'],['../group___r_c_c___l_s_e___config.html',1,'LSE Config'],['../group___r_c_c___l_s_e_drive___config.html',1,'LSE Drive Config'],['../group___r_c_c___l_s_i___config.html',1,'LSI Config'],['../group___r_c_c___m_s_i___config.html',1,'MSI Config'],['../group___r_c_c___p_l_l___config.html',1,'PLL Config']]],
  ['configuration_103',['RCC RTC Clock Configuration',['../group___r_c_c___r_t_c___clock___configuration.html',1,'']]],
  ['configuration_20definition_104',['I2C Interrupt configuration definition',['../group___i2_c___interrupt__configuration__definition.html',1,'']]],
  ['configuration_20functions_105',['Configuration functions',['../group___e_x_t_i___exported___functions___group1.html',1,'Configuration functions'],['../group___c_o_r_t_e_x___exported___functions___group1.html',1,'Initialization and Configuration functions']]],
  ['configuration_20structure_20definition_106',['I2C Configuration Structure definition',['../group___i2_c___configuration___structure__definition.html',1,'']]],
  ['configuration_5fsection_5ffor_5fcmsis_107',['Configuration_section_for_CMSIS',['../group___configuration__section__for___c_m_s_i_s.html',1,'']]],
  ['conjugate_108',['Conjugate',['../group__cmplx__conj.html',1,'Complex Conjugate'],['../group___quat_conjugate.html',1,'Quaternion Conjugate']]],
  ['constants_109',['Constants',['../group___a_d_c___exported___constants.html',1,'ADC Exported Constants'],['../group___a_d_c_ex___exported___constants.html',1,'ADC Extended Exported Constants'],['../group___a_d_c___private___constants.html',1,'ADC Private Constants'],['../group___c_o_r_t_e_x___exported___constants.html',1,'CORTEX Exported Constants'],['../group___c_o_r_t_e_x___l_l___exported___constants.html',1,'CORTEX Exported Constants'],['../group___d_m_a___exported___constants.html',1,'DMA Exported Constants'],['../group___e_x_t_i___exported___constants.html',1,'EXTI Exported Constants'],['../group___e_x_t_i___private___constants.html',1,'EXTI Private Constants'],['../group___f_l_a_s_h___exported___constants.html',1,'FLASH Exported Constants'],['../group___f_l_a_s_h___private___constants.html',1,'FLASH Private Constants'],['../group___g_p_i_o___exported___constants.html',1,'GPIO Exported Constants'],['../group___g_p_i_o___private___constants.html',1,'GPIO Private Constants'],['../group___g_p_i_o_ex___exported___constants.html',1,'GPIOEx Exported Constants'],['../group___h_a_l___exported___constants.html',1,'HAL Exported Constants'],['../group___i2_c___exported___constants.html',1,'I2C Exported Constants'],['../group___i2_c_ex___exported___constants.html',1,'I2C Extended Exported Constants'],['../group___i2_c_ex___private___constants.html',1,'I2C Extended Private Constants'],['../group___i2_c___private___constants.html',1,'I2C Private Constants'],['../group___p_w_r___exported___constants.html',1,'PWR Exported Constants'],['../group___p_w_r_ex___exported___constants.html',1,'PWR Extended Exported Constants'],['../group___r_c_c___exported___constants.html',1,'RCC Exported Constants'],['../group___r_c_c___private___constants.html',1,'RCC Private Constants'],['../group___r_c_c_ex___exported___constants.html',1,'RCCEx Exported Constants'],['../group___s_p_i___exported___constants.html',1,'SPI Exported Constants'],['../group___s_y_s_c_f_g___exported___constants.html',1,'SYSCFG Exported Constants'],['../group___t_i_m___exported___constants.html',1,'TIM Exported Constants'],['../group___t_i_m_ex___exported___constants.html',1,'TIM Extended Exported Constants'],['../group___t_i_m___private___constants.html',1,'TIM Private Constants'],['../group___u_a_r_t___exported___constants.html',1,'UART Exported Constants'],['../group___u_a_r_t_ex___exported___constants.html',1,'UARTEx Exported Constants'],['../group___u_t_i_l_s___l_l___exported___constants.html',1,'UTILS Exported Constants'],['../group___u_t_i_l_s___l_l___private___constants.html',1,'UTILS Private Constants']]],
  ['constants_110',['Shift to apply to retrieve polarity information from PWR_WAKEUP_PINy_xxx constants',['../group___p_w_r_ex___w_u_p___polarity.html',1,'']]],
  ['control_111',['Control',['../group___p_i_d.html',1,'PID Motor Control'],['../group___u_a_r_t___hardware___flow___control.html',1,'UART Hardware Flow Control']]],
  ['control_20block_20scb_112',['System Control Block (SCB)',['../group___c_m_s_i_s___s_c_b.html',1,'']]],
  ['control_20functions_113',['Control functions',['../group___p_w_r_ex___exported___functions___group1.html',1,'Extended Peripheral Control functions'],['../group___t_i_m_ex___exported___functions___group5.html',1,'Extended Peripheral Control functions'],['../group___c_o_r_t_e_x___exported___functions___group2.html',1,'Peripheral Control functions'],['../group___a_d_c___exported___functions___group3.html',1,'Peripheral Control functions'],['../group___p_w_r___exported___functions___group2.html',1,'Peripheral Control functions'],['../group___u_a_r_t___exported___functions___group3.html',1,'Peripheral Control functions'],['../group___t_i_m___exported___functions___group8.html',1,'TIM Peripheral Control functions']]],
  ['control_20registers_114',['Status and Control Registers',['../group___c_m_s_i_s___c_o_r_e.html',1,'']]],
  ['controller_20functions_115',['Controller Functions',['../group__group_controller.html',1,'']]],
  ['controller_20nvic_116',['Nested Vectored Interrupt Controller (NVIC)',['../group___c_m_s_i_s___n_v_i_c.html',1,'']]],
  ['controls_20not_20in_20scb_20scnscb_117',['System Controls not in SCB (SCnSCB)',['../group___c_m_s_i_s___s_cn_s_c_b.html',1,'']]],
  ['conversion_20data_118',['ADC group regular - Overrun behavior on conversion data',['../group___a_d_c___h_a_l___e_c___r_e_g___o_v_r___d_a_t_a___b_e_h_a_v_i_o_r.html',1,'']]],
  ['conversion_20data_20alignment_119',['ADC conversion data alignment',['../group___a_d_c___h_a_l___e_c___d_a_t_a___a_l_i_g_n.html',1,'']]],
  ['conversion_20or_20sequence_20conversions_120',['ADC sequencer end of unitary conversion or sequence conversions',['../group___a_d_c___e_o_c_selection.html',1,'']]],
  ['conversions_121',['conversions',['../group___a_d_c___e_o_c_selection.html',1,'ADC sequencer end of unitary conversion or sequence conversions'],['../group___quat_conv.html',1,'Quaternion conversions']]],
  ['convert_2016_20bit_20fixed_20point_20value_122',['Convert 16-bit fixed point value',['../group__q15__to__x.html',1,'']]],
  ['convert_2032_20bit_20fixed_20point_20value_123',['Convert 32-bit fixed point value',['../group__q31__to__x.html',1,'']]],
  ['convert_2032_20bit_20floating_20point_20value_124',['Convert 32-bit floating point value',['../group__float__to__x.html',1,'']]],
  ['convert_208_20bit_20fixed_20point_20value_125',['Convert 8-bit fixed point value',['../group__q7__to__x.html',1,'']]],
  ['convolution_126',['Convolution',['../group___conv.html',1,'Convolution'],['../group___partial_conv.html',1,'Partial Convolution']]],
  ['copy_127',['Vector Copy',['../group__copy.html',1,'']]],
  ['core_20debug_20registers_20coredebug_128',['Core Debug Registers (CoreDebug)',['../group___c_m_s_i_s___core_debug.html',1,'']]],
  ['core_20definitions_129',['Core Definitions',['../group___c_m_s_i_s__core__base.html',1,'']]],
  ['core_20instruction_20interface_130',['CMSIS Core Instruction Interface',['../group___c_m_s_i_s___core___instruction_interface.html',1,'']]],
  ['core_20register_20access_20functions_131',['CMSIS Core Register Access Functions',['../group___c_m_s_i_s___core___reg_acc_functions.html',1,'']]],
  ['core_20register_20bit_20field_20macros_132',['Core register bit field macros',['../group___c_m_s_i_s__core__bitfield.html',1,'']]],
  ['coredebug_133',['Core Debug Registers (CoreDebug)',['../group___c_m_s_i_s___core_debug.html',1,'']]],
  ['correlation_134',['Correlation',['../group___corr.html',1,'Correlation'],['../group___correlation.html',1,'Correlation']]],
  ['cortex_135',['CORTEX',['../group___c_o_r_t_e_x.html',1,'CORTEX'],['../group___c_o_r_t_e_x___l_l.html',1,'CORTEX']]],
  ['cortex_20aliased_20defines_20maintained_20for_20legacy_20purpose_136',['HAL CORTEX Aliased Defines maintained for legacy purpose',['../group___h_a_l___c_o_r_t_e_x___aliased___defines.html',1,'']]],
  ['cortex_20exported_20constants_137',['CORTEX Exported Constants',['../group___c_o_r_t_e_x___exported___constants.html',1,'CORTEX Exported Constants'],['../group___c_o_r_t_e_x___l_l___exported___constants.html',1,'CORTEX Exported Constants']]],
  ['cortex_20exported_20functions_138',['CORTEX Exported Functions',['../group___c_o_r_t_e_x___exported___functions.html',1,'CORTEX Exported Functions'],['../group___c_o_r_t_e_x___l_l___exported___functions.html',1,'CORTEX Exported Functions']]],
  ['cortex_20exported_20macros_139',['CORTEX Exported Macros',['../group___c_o_r_t_e_x___exported___macros.html',1,'']]],
  ['cortex_20exported_20types_140',['CORTEX Exported Types',['../group___c_o_r_t_e_x___exported___types.html',1,'']]],
  ['cortex_20preemption_20priority_20group_141',['CORTEX Preemption Priority Group',['../group___c_o_r_t_e_x___preemption___priority___group.html',1,'']]],
  ['cortex_20private_20macros_142',['CORTEX Private Macros',['../group___c_o_r_t_e_x___private___macros.html',1,'']]],
  ['cortex_20systick_20clock_20source_143',['CORTEX SysTick clock source',['../group___c_o_r_t_e_x___sys_tick__clock__source.html',1,'']]],
  ['cosine_144',['Cosine',['../group__cos.html',1,'Cosine'],['../group___sin_cos.html',1,'Sine Cosine']]],
  ['cosinedist_145',['CosineDist',['../group___cosine_dist.html',1,'']]],
  ['counter_20mode_146',['TIM Counter Mode',['../group___t_i_m___counter___mode.html',1,'']]],
  ['cr1_20register_147',['CR1 Register',['../group___u_a_r_t___c_r1___d_e_a_t___a_d_d_r_e_s_s___l_s_b___p_o_s.html',1,'UART Driver Enable Assertion Time LSB Position In CR1 Register'],['../group___u_a_r_t___c_r1___d_e_d_t___a_d_d_r_e_s_s___l_s_b___p_o_s.html',1,'UART Driver Enable DeAssertion Time LSB Position In CR1 Register']]],
  ['cr2_20register_148',['UART Address-matching LSB Position In CR2 Register',['../group___u_a_r_t___c_r2___a_d_d_r_e_s_s___l_s_b___p_o_s.html',1,'']]],
  ['crc_20aliased_20defines_20maintained_20for_20legacy_20purpose_149',['HAL CRC Aliased Defines maintained for legacy purpose',['../group___h_a_l___c_r_c___aliased___defines.html',1,'']]],
  ['crc_20api_20aliases_150',['CRC API aliases',['../group___c_r_c___aliases.html',1,'']]],
  ['crc_20calculation_151',['SPI CRC Calculation',['../group___s_p_i___c_r_c___calculation.html',1,'']]],
  ['crc_20length_152',['SPI CRC Length',['../group___s_p_i___c_r_c__length.html',1,'']]],
  ['crdelay_153',['crDELAY',['../group__cr_d_e_l_a_y.html',1,'']]],
  ['crqueue_5freceive_154',['crQUEUE_RECEIVE',['../group__cr_q_u_e_u_e___r_e_c_e_i_v_e.html',1,'']]],
  ['crqueue_5freceive_5ffrom_5fisr_155',['crQUEUE_RECEIVE_FROM_ISR',['../group__cr_q_u_e_u_e___r_e_c_e_i_v_e___f_r_o_m___i_s_r.html',1,'']]],
  ['crqueue_5fsend_156',['crQUEUE_SEND',['../group__cr_q_u_e_u_e___s_e_n_d.html',1,'']]],
  ['crqueue_5fsend_5ffrom_5fisr_157',['crQUEUE_SEND_FROM_ISR',['../group__cr_q_u_e_u_e___s_e_n_d___f_r_o_m___i_s_r.html',1,'']]],
  ['crstart_158',['crSTART',['../group__cr_s_t_a_r_t.html',1,'']]],
  ['cryp_20aliased_20defines_20maintained_20for_20legacy_20purpose_159',['HAL CRYP Aliased Defines maintained for legacy purpose',['../group___h_a_l___a_e_s___aliased___defines.html',1,'']]],
  ['cryp_20aliased_20functions_20maintained_20for_20legacy_20purpose_160',['HAL CRYP Aliased Functions maintained for legacy purpose',['../group___h_a_l___c_r_y_p___aliased___functions.html',1,'']]],
  ['cryp_20aliased_20macros_20maintained_20for_20legacy_20purpose_161',['HAL CRYP Aliased Macros maintained for legacy purpose',['../group___h_a_l___a_e_s___aliased___macros.html',1,'']]],
  ['css_20external_20interrupt_20line_162',['RCC LSE CSS external interrupt line',['../group___r_c_c_ex___e_x_t_i___l_i_n_e___l_s_e_c_s_s.html',1,'']]],
  ['cubic_20spline_20interpolation_163',['Cubic Spline Interpolation',['../group___spline_interpolate.html',1,'']]]
];
