var searchData=
[
  ['value_0',['Vector Absolute Value',['../group___basic_abs.html',1,'']]],
  ['value_1',['value',['../group__q15__to__x.html',1,'Convert 16-bit fixed point value'],['../group__q31__to__x.html',1,'Convert 32-bit fixed point value'],['../group__float__to__x.html',1,'Convert 32-bit floating point value'],['../group__q7__to__x.html',1,'Convert 8-bit fixed point value'],['../group___u_a_r_t___time_out___value.html',1,'UART polling-based communications time-out value']]],
  ['values_2',['Timeout Values',['../group___r_c_c___timeout___value.html',1,'']]],
  ['values_3',['values',['../group___u_a_r_t___reception___type___values.html',1,'UART Reception type values'],['../group___u_a_r_t___rx_event___type___values.html',1,'UART RxEvent type values']]],
  ['variables_4',['FLASH Private Variables',['../group___f_l_a_s_h___private___variables.html',1,'']]],
  ['variance_5',['Variance',['../group__variance.html',1,'']]],
  ['vcoroutineschedule_6',['vCoRoutineSchedule',['../group__v_co_routine_schedule.html',1,'']]],
  ['vector_7',['Householder transform of a vector',['../group___matrix_householder.html',1,'']]],
  ['vector_20absolute_20value_8',['Vector Absolute Value',['../group___basic_abs.html',1,'']]],
  ['vector_20addition_9',['Vector Addition',['../group___basic_add.html',1,'']]],
  ['vector_20bitwise_20and_10',['Vector bitwise AND',['../group___and.html',1,'']]],
  ['vector_20bitwise_20exclusive_20or_11',['Vector bitwise exclusive OR',['../group___xor.html',1,'']]],
  ['vector_20bitwise_20inclusive_20or_12',['Vector bitwise inclusive OR',['../group___or.html',1,'']]],
  ['vector_20bitwise_20not_13',['Vector bitwise NOT',['../group___not.html',1,'']]],
  ['vector_20clarke_20transform_14',['Vector Clarke Transform',['../group__clarke.html',1,'']]],
  ['vector_20copy_15',['Vector Copy',['../group__copy.html',1,'']]],
  ['vector_20dot_20product_16',['Vector Dot Product',['../group___basic_dot_prod.html',1,'']]],
  ['vector_20exponential_17',['Vector Exponential',['../group__vexp.html',1,'']]],
  ['vector_20fill_18',['Vector Fill',['../group___fill.html',1,'']]],
  ['vector_20inverse_20clarke_20transform_19',['Vector Inverse Clarke Transform',['../group__inv__clarke.html',1,'']]],
  ['vector_20inverse_20park_20transform_20',['Vector Inverse Park transform',['../group__inv__park.html',1,'']]],
  ['vector_20log_21',['Vector Log',['../group__vlog.html',1,'']]],
  ['vector_20multiplication_22',['Vector Multiplication',['../group___matrix_vect_mult.html',1,'Matrix Vector Multiplication'],['../group___basic_mult.html',1,'Vector Multiplication']]],
  ['vector_20negate_23',['Vector Negate',['../group___basic_negate.html',1,'']]],
  ['vector_20offset_24',['Vector Offset',['../group___basic_offset.html',1,'']]],
  ['vector_20park_20transform_25',['Vector Park Transform',['../group__park.html',1,'']]],
  ['vector_20scale_26',['Vector Scale',['../group___basic_scale.html',1,'']]],
  ['vector_20shift_27',['Vector Shift',['../group___basic_shift.html',1,'']]],
  ['vector_20sorting_20algorithms_28',['Vector sorting algorithms',['../group___sorting.html',1,'']]],
  ['vector_20subtraction_29',['Vector Subtraction',['../group___basic_sub.html',1,'']]],
  ['vectored_20interrupt_20controller_20nvic_30',['Nested Vectored Interrupt Controller (NVIC)',['../group___c_m_s_i_s___n_v_i_c.html',1,'']]],
  ['view_31',['I2C Transfer Direction Master Point of View',['../group___i2_c___x_f_e_r_d_i_r_e_c_t_i_o_n.html',1,'']]],
  ['voltage_20detection_20levels_32',['Programmable Voltage Detection levels',['../group___p_w_r___p_v_d__detection__level.html',1,'']]],
  ['voltage_20monitoring_20type_33',['Peripheral Voltage Monitoring type',['../group___p_w_r_ex___p_v_m___type.html',1,'']]],
  ['voltage_20scale_34',['PWR Regulator voltage scale',['../group___p_w_r_ex___regulator___voltage___scale.html',1,'']]],
  ['vqueuedelete_35',['vQueueDelete',['../group__v_queue_delete.html',1,'']]],
  ['vsemaphorecreatebinary_36',['vSemaphoreCreateBinary',['../group__v_semaphore_create_binary.html',1,'']]],
  ['vsemaphoredelete_37',['vSemaphoreDelete',['../group__v_semaphore_delete.html',1,'']]],
  ['vstreambufferdelete_38',['vStreamBufferDelete',['../group__v_stream_buffer_delete.html',1,'']]],
  ['vtaskdelay_39',['vTaskDelay',['../group__v_task_delay.html',1,'']]],
  ['vtaskdelayuntil_40',['vTaskDelayUntil',['../group__v_task_delay_until.html',1,'']]],
  ['vtaskdelete_41',['vTaskDelete',['../group__v_task_delete.html',1,'']]],
  ['vtaskendscheduler_42',['vTaskEndScheduler',['../group__v_task_end_scheduler.html',1,'']]],
  ['vtaskgetinfo_43',['vTaskGetInfo',['../group__v_task_get_info.html',1,'']]],
  ['vtaskgetruntimestats_44',['vTaskGetRunTimeStats',['../group__v_task_get_run_time_stats.html',1,'']]],
  ['vtasklist_45',['vTaskList',['../group__v_task_list.html',1,'']]],
  ['vtaskpriorityset_46',['vTaskPrioritySet',['../group__v_task_priority_set.html',1,'']]],
  ['vtaskresume_47',['vTaskResume',['../group__v_task_resume.html',1,'']]],
  ['vtaskresumefromisr_48',['vTaskResumeFromISR',['../group__v_task_resume_from_i_s_r.html',1,'']]],
  ['vtasksettimeoutstate_49',['vTaskSetTimeOutState',['../group__v_task_set_time_out_state.html',1,'']]],
  ['vtaskstartscheduler_50',['vTaskStartScheduler',['../group__v_task_start_scheduler.html',1,'']]],
  ['vtasksuspend_51',['vTaskSuspend',['../group__v_task_suspend.html',1,'']]],
  ['vtasksuspendall_52',['vTaskSuspendAll',['../group__v_task_suspend_all.html',1,'']]]
];
