var searchData=
[
  ['sai_20aliased_20macros_20maintained_20for_20legacy_20purpose_0',['HAL SAI Aliased Macros maintained for legacy purpose',['../group___h_a_l___s_a_i___aliased___macros.html',1,'']]],
  ['sampling_1',['UART Over Sampling',['../group___u_a_r_t___over___sampling.html',1,'']]],
  ['sampling_20method_2',['UART One Bit Sampling Method',['../group___u_a_r_t___one_bit___sampling.html',1,'']]],
  ['sampling_20time_3',['Channel - Sampling time',['../group___a_d_c___h_a_l___e_c___c_h_a_n_n_e_l___s_a_m_p_l_i_n_g_t_i_m_e.html',1,'']]],
  ['sau_20functions_4',['SAU Functions',['../group___c_m_s_i_s___core___s_a_u_functions.html',1,'']]],
  ['scale_5',['Scale',['../group___matrix_scale.html',1,'Matrix Scale'],['../group___basic_scale.html',1,'Vector Scale']]],
  ['scale_6',['PWR Regulator voltage scale',['../group___p_w_r_ex___regulator___voltage___scale.html',1,'']]],
  ['scan_20mode_7',['ADC sequencer scan mode',['../group___a_d_c___scan__mode.html',1,'']]],
  ['scb_8',['System Control Block (SCB)',['../group___c_m_s_i_s___s_c_b.html',1,'']]],
  ['scb_20scnscb_9',['System Controls not in SCB (SCnSCB)',['../group___c_m_s_i_s___s_cn_s_c_b.html',1,'']]],
  ['scnscb_10',['System Controls not in SCB (SCnSCB)',['../group___c_m_s_i_s___s_cn_s_c_b.html',1,'']]],
  ['scope_20for_20adc_20group_20regular_11',['Oversampling - Oversampling scope for ADC group regular',['../group___a_d_c___h_a_l___e_c___o_v_s___s_c_o_p_e___r_e_g.html',1,'']]],
  ['sd_20mmc_20aliased_20macros_20maintained_20for_20legacy_20purpose_12',['HAL SD/MMC Aliased Macros maintained for legacy purpose',['../group___h_a_l___s_d___aliased___macros.html',1,'']]],
  ['select_20management_13',['SPI Slave Select Management',['../group___s_p_i___slave___select__management.html',1,'']]],
  ['selected_14',['selected',['../group___a_d_c__injected__external__trigger__edge.html',1,'ADC group injected trigger edge (when external trigger is selected)'],['../group___a_d_c__regular__external__trigger__edge.html',1,'ADC group regular trigger edge (when external trigger is selected)']]],
  ['selection_15',['Selection',['../group___r_c_c_ex___periph___clock___selection.html',1,'Periph Clock Selection'],['../group___t_i_m___input___capture___selection.html',1,'TIM Input Capture Selection'],['../group___t_i_m___master___mode___selection.html',1,'TIM Master Mode Selection'],['../group___t_i_m___t_i1___selection.html',1,'TIM TI1 Input Selection'],['../group___t_i_m___trigger___selection.html',1,'TIM Trigger Selection'],['../group___u_a_r_t___half___duplex___selection.html',1,'UART Half Duplex Selection'],['../group___u_a_r_t___wake_up__from___stop___selection.html',1,'UART WakeUp From Stop Selection']]],
  ['selection_16',['selection',['../group___t_i_m___c_c___d_m_a___request.html',1,'CCx DMA request selection'],['../group___g_p_i_o_ex___alternate__function__selection.html',1,'GPIOEx Alternate function selection'],['../group___p_w_r_ex___v_b_a_t___battery___charging___selection.html',1,'PWR battery charging resistor selection']]],
  ['selection_202_20trgo2_17',['TIM Master Mode Selection 2 (TRGO2)',['../group___t_i_m___master___mode___selection__2.html',1,'']]],
  ['selection_20for_20idle_20mode_20state_18',['TIM OSSI OffState Selection for Idle mode state',['../group___t_i_m___o_s_s_i___off___state___selection__for___idle__mode__state.html',1,'']]],
  ['selection_20for_20run_20mode_20state_19',['TIM OSSR OffState Selection for Run mode state',['../group___t_i_m___o_s_s_r___off___state___selection__for___run__mode__state.html',1,'']]],
  ['sensor_20functions_20',['Extended Timer Hall Sensor functions',['../group___t_i_m_ex___exported___functions___group1.html',1,'']]],
  ['sequence_20conversions_21',['ADC sequencer end of unitary conversion or sequence conversions',['../group___a_d_c___e_o_c_selection.html',1,'']]],
  ['sequencer_20end_20of_20unitary_20conversion_20or_20sequence_20conversions_22',['ADC sequencer end of unitary conversion or sequence conversions',['../group___a_d_c___e_o_c_selection.html',1,'']]],
  ['sequencer_20ranks_23',['Sequencer ranks',['../group___a_d_c___i_n_j___s_e_q___r_a_n_k_s.html',1,'ADC group injected - Sequencer ranks'],['../group___a_d_c___h_a_l___e_c___r_e_g___s_e_q___r_a_n_k_s.html',1,'ADC group regular - Sequencer ranks']]],
  ['sequencer_20scan_20mode_24',['ADC sequencer scan mode',['../group___a_d_c___scan__mode.html',1,'']]],
  ['sequential_20transfer_20options_25',['I2C Sequential Transfer Options',['../group___i2_c___x_f_e_r_o_p_t_i_o_n_s.html',1,'']]],
  ['setting_20in_20standby_20shutdown_20mode_26',['GPIO bit number for I/O setting in standby/shutdown mode',['../group___p_w_r_ex___g_p_i_o___bit___number.html',1,'']]],
  ['shift_27',['Vector Shift',['../group___basic_shift.html',1,'']]],
  ['shift_28',['Oversampling - Data shift',['../group___a_d_c___h_a_l___e_c___o_v_s___s_h_i_f_t.html',1,'']]],
  ['shift_20to_20apply_20to_20retrieve_20polarity_20information_20from_20pwr_5fwakeup_5fpiny_5fxxx_20constants_29',['Shift to apply to retrieve polarity information from PWR_WAKEUP_PINy_xxx constants',['../group___p_w_r_ex___w_u_p___polarity.html',1,'']]],
  ['shutdown_30',['FLASH Option Bytes User Reset On Shutdown',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_h_u_t_d_o_w_n.html',1,'']]],
  ['shutdown_20mode_31',['GPIO bit number for I/O setting in standby/shutdown mode',['../group___p_w_r_ex___g_p_i_o___bit___number.html',1,'']]],
  ['sigmoid_20svm_32',['Sigmoid SVM',['../group__sigmoidsvm.html',1,'']]],
  ['signature_33',['DEVICE ELECTRONIC SIGNATURE',['../group___u_t_i_l_s___e_f___d_e_v_i_c_e___e_l_e_c_t_r_o_n_i_c___s_i_g_n_a_t_u_r_e.html',1,'']]],
  ['simd_20intrinsics_34',['CMSIS SIMD Intrinsics',['../group___c_m_s_i_s___s_i_m_d__intrinsics.html',1,'']]],
  ['sine_35',['Sine',['../group__sin.html',1,'']]],
  ['sine_20cosine_36',['Sine Cosine',['../group___sin_cos.html',1,'']]],
  ['single_20or_20differential_20ending_37',['Channel - Single or differential ending',['../group___a_d_c___h_a_l___e_c___c_h_a_n_n_e_l___s_i_n_g_l_e___d_i_f_f___e_n_d_i_n_g.html',1,'']]],
  ['size_38',['Size',['../group___i2_c___m_e_m_o_r_y___a_d_d_r_e_s_s___s_i_z_e.html',1,'I2C Memory Address Size'],['../group___s_p_i___data___size.html',1,'SPI Data Size']]],
  ['size_39',['size',['../group___d_m_a___memory__data__size.html',1,'DMA Memory data size'],['../group___d_m_a___peripheral__data__size.html',1,'DMA Peripheral data size']]],
  ['slave_20mode_40',['TIM Master/Slave Mode',['../group___t_i_m___master___slave___mode.html',1,'']]],
  ['slave_20mode_41',['TIM Slave mode',['../group___t_i_m___slave___mode.html',1,'']]],
  ['slave_20select_20management_42',['SPI Slave Select Management',['../group___s_p_i___slave___select__management.html',1,'']]],
  ['sleep_20enable_20disable_43',['Sleep Enable Disable',['../group___r_c_c___a_h_b1___clock___sleep___enable___disable.html',1,'AHB1 Peripheral Clock Sleep Enable Disable'],['../group___r_c_c___a_h_b2___clock___sleep___enable___disable.html',1,'AHB2 Peripheral Clock Sleep Enable Disable'],['../group___r_c_c___a_h_b3___clock___sleep___enable___disable.html',1,'AHB3 Peripheral Clock Sleep Enable Disable'],['../group___r_c_c___a_p_b1___clock___sleep___enable___disable.html',1,'APB1 Peripheral Clock Sleep Enable Disable'],['../group___r_c_c___a_p_b2___clock___sleep___enable___disable.html',1,'APB2 Peripheral Clock Sleep Enable Disable']]],
  ['sleep_20enabled_20or_20disabled_20status_44',['Sleep Enabled or Disabled Status',['../group___r_c_c___a_h_b1___clock___sleep___enable___disable___status.html',1,'AHB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_h_b2___clock___sleep___enable___disable___status.html',1,'AHB2 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_h_b3___clock___sleep___enable___disable___status.html',1,'AHB3 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b1___clock___sleep___enable___disable___status.html',1,'APB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b2___clock___sleep___enable___disable___status.html',1,'APB2 Peripheral Clock Sleep Enabled or Disabled Status']]],
  ['sleep_20mode_20entry_45',['PWR SLEEP mode entry',['../group___p_w_r___s_l_e_e_p__mode__entry.html',1,'']]],
  ['smartcard_20aliased_20defines_20maintained_20for_20legacy_20purpose_46',['HAL SMARTCARD Aliased Defines maintained for legacy purpose',['../group___h_a_l___s_m_a_r_t_c_a_r_d___aliased___defines.html',1,'']]],
  ['smartcard_20aliased_20macros_20maintained_20for_20legacy_20purpose_47',['HAL SMARTCARD Aliased Macros maintained for legacy purpose',['../group___h_a_l___s_m_a_r_t_c_a_r_d___aliased___macros.html',1,'']]],
  ['smbus_20aliased_20defines_20maintained_20for_20legacy_20purpose_48',['HAL SMBUS Aliased Defines maintained for legacy purpose',['../group___h_a_l___s_m_b_u_s___aliased___defines.html',1,'']]],
  ['smbus_20aliased_20functions_20maintained_20for_20legacy_20purpose_49',['HAL SMBUS Aliased Functions maintained for legacy purpose',['../group___h_a_l___s_m_b_u_s___aliased___functions.html',1,'']]],
  ['smbus_20aliased_20macros_20maintained_20for_20legacy_20purpose_50',['HAL SMBUS Aliased Macros maintained for legacy purpose',['../group___h_a_l___s_m_b_u_s___aliased___macros.html',1,'']]],
  ['smpr1_20fields_51',['ADCx SMPR1 fields',['../group___a_d_c___s_m_p_r1__fields.html',1,'']]],
  ['sorting_20algorithms_52',['Vector sorting algorithms',['../group___sorting.html',1,'']]],
  ['source_53',['Source',['../group___r_c_c_ex___a_d_c___clock___source.html',1,'ADC Clock Source'],['../group___r_c_c___a_h_b___clock___source.html',1,'AHB Clock Source'],['../group___r_c_c___a_p_b1___a_p_b2___clock___source.html',1,'APB1 APB2 Clock Source'],['../group___r_c_c_ex___i2_c1___clock___source.html',1,'I2C1 Clock Source'],['../group___r_c_c_ex___i2_c3___clock___source.html',1,'I2C3 Clock Source'],['../group___r_c_c_ex___l_s_c_o___clock___source.html',1,'Low Speed Clock Source'],['../group___r_c_c_ex___l_p_t_i_m1___clock___source.html',1,'LPTIM1 Clock Source'],['../group___r_c_c_ex___l_p_t_i_m2___clock___source.html',1,'LPTIM2 Clock Source'],['../group___r_c_c_ex___l_p_u_a_r_t1___clock___source.html',1,'LPUART1 Clock Source'],['../group___r_c_c___m_c_o1___clock___source.html',1,'MCO1 Clock Source'],['../group___r_c_c___p_l_l___clock___source.html',1,'PLL Clock Source'],['../group___r_c_c_ex___r_n_g___clock___source.html',1,'RNG Clock Source'],['../group___r_c_c___r_t_c___clock___source.html',1,'RTC Clock Source'],['../group___r_c_c___system___clock___source.html',1,'System Clock Source'],['../group___c_o_r_t_e_x___l_l___e_c___c_l_k_s_o_u_r_c_e___h_c_l_k.html',1,'SYSTICK Clock Source'],['../group___t_i_m___clear_input___source.html',1,'TIM Clear Input Source'],['../group___t_i_m___clock___source.html',1,'TIM Clock Source'],['../group___t_i_m___commutation___source.html',1,'TIM Commutation Source'],['../group___t_i_m___event___source.html',1,'TIM Event Source'],['../group___r_c_c_ex___u_s_a_r_t1___clock___source.html',1,'USART1 Clock Source'],['../group___r_c_c_ex___u_s_a_r_t2___clock___source.html',1,'USART2 Clock Source']]],
  ['source_54',['source',['../group___a_d_c___h_a_l___e_c___c_o_m_m_o_n___c_l_o_c_k___s_o_u_r_c_e.html',1,'ADC common - Clock source'],['../group___a_d_c__injected__external__trigger__source.html',1,'ADC group injected trigger source'],['../group___a_d_c__regular__external__trigger__source.html',1,'ADC group regular trigger source'],['../group___c_o_r_t_e_x___sys_tick__clock__source.html',1,'CORTEX SysTick clock source'],['../group___t_i_m_ex___break___input___source.html',1,'TIM Extended Break input source']]],
  ['source_20enabling_55',['TIM Extended Break input source enabling',['../group___t_i_m_ex___break___input___source___enable.html',1,'']]],
  ['source_20status_56',['System Clock Source Status',['../group___r_c_c___system___clock___source___status.html',1,'']]],
  ['sources_57',['TIM DMA Sources',['../group___t_i_m___d_m_a__sources.html',1,'']]],
  ['sparse_20filters_58',['Finite Impulse Response (FIR) Sparse Filters',['../group___f_i_r___sparse.html',1,'']]],
  ['spdifrx_20aliased_20macros_20maintained_20for_20legacy_20purpose_59',['HAL SPDIFRX Aliased Macros maintained for legacy purpose',['../group___h_a_l___s_p_d_i_f_r_x___aliased___macros.html',1,'']]],
  ['speed_60',['GPIO speed',['../group___g_p_i_o__speed.html',1,'']]],
  ['speed_20clock_20source_61',['Low Speed Clock Source',['../group___r_c_c_ex___l_s_c_o___clock___source.html',1,'']]],
  ['spi_62',['SPI',['../group___s_p_i.html',1,'']]],
  ['spi_20aliased_20defines_20maintained_20for_20legacy_20purpose_63',['HAL SPI Aliased Defines maintained for legacy purpose',['../group___h_a_l___s_p_i___aliased___defines.html',1,'']]],
  ['spi_20aliased_20functions_20maintained_20for_20legacy_20purpose_64',['HAL SPI Aliased Functions maintained for legacy purpose',['../group___h_a_l___s_p_i___aliased___functions.html',1,'']]],
  ['spi_20aliased_20macros_20maintained_20for_20legacy_20purpose_65',['HAL SPI Aliased Macros maintained for legacy purpose',['../group___h_a_l___s_p_i___aliased___macros.html',1,'']]],
  ['spi_20baudrate_20prescaler_66',['SPI BaudRate Prescaler',['../group___s_p_i___baud_rate___prescaler.html',1,'']]],
  ['spi_20clock_20phase_67',['SPI Clock Phase',['../group___s_p_i___clock___phase.html',1,'']]],
  ['spi_20clock_20polarity_68',['SPI Clock Polarity',['../group___s_p_i___clock___polarity.html',1,'']]],
  ['spi_20crc_20calculation_69',['SPI CRC Calculation',['../group___s_p_i___c_r_c___calculation.html',1,'']]],
  ['spi_20crc_20length_70',['SPI CRC Length',['../group___s_p_i___c_r_c__length.html',1,'']]],
  ['spi_20data_20size_71',['SPI Data Size',['../group___s_p_i___data___size.html',1,'']]],
  ['spi_20direction_20mode_72',['SPI Direction Mode',['../group___s_p_i___direction.html',1,'']]],
  ['spi_20error_20code_73',['SPI Error Code',['../group___s_p_i___error___code.html',1,'']]],
  ['spi_20exported_20constants_74',['SPI Exported Constants',['../group___s_p_i___exported___constants.html',1,'']]],
  ['spi_20exported_20macros_75',['SPI Exported Macros',['../group___s_p_i___exported___macros.html',1,'']]],
  ['spi_20exported_20types_76',['SPI Exported Types',['../group___s_p_i___exported___types.html',1,'']]],
  ['spi_20fifo_20reception_20threshold_77',['SPI FIFO Reception Threshold',['../group___s_p_i___f_i_f_o__reception__threshold.html',1,'']]],
  ['spi_20flags_20definition_78',['SPI Flags Definition',['../group___s_p_i___flags__definition.html',1,'']]],
  ['spi_20interrupt_20definition_79',['SPI Interrupt Definition',['../group___s_p_i___interrupt__definition.html',1,'']]],
  ['spi_20mode_80',['SPI Mode',['../group___s_p_i___mode.html',1,'']]],
  ['spi_20msb_20lsb_20transmission_81',['SPI MSB LSB Transmission',['../group___s_p_i___m_s_b___l_s_b__transmission.html',1,'']]],
  ['spi_20nss_20pulse_20mode_82',['SPI NSS Pulse Mode',['../group___s_p_i___n_s_s_p___mode.html',1,'']]],
  ['spi_20private_20macros_83',['SPI Private Macros',['../group___s_p_i___private___macros.html',1,'']]],
  ['spi_20reception_20fifo_20status_20level_84',['SPI Reception FIFO Status Level',['../group___s_p_i__reception__fifo__status__level.html',1,'']]],
  ['spi_20slave_20select_20management_85',['SPI Slave Select Management',['../group___s_p_i___slave___select__management.html',1,'']]],
  ['spi_20ti_20mode_86',['SPI TI Mode',['../group___s_p_i___t_i__mode.html',1,'']]],
  ['spi_20transmission_20fifo_20status_20level_87',['SPI Transmission FIFO Status Level',['../group___s_p_i__transmission__fifo__status__level.html',1,'']]],
  ['spi_5fexported_5ffunctions_88',['SPI_Exported_Functions',['../group___s_p_i___exported___functions.html',1,'']]],
  ['spi_5fexported_5ffunctions_5fgroup1_89',['SPI_Exported_Functions_Group1',['../group___s_p_i___exported___functions___group1.html',1,'']]],
  ['spi_5fexported_5ffunctions_5fgroup2_90',['SPI_Exported_Functions_Group2',['../group___s_p_i___exported___functions___group2.html',1,'']]],
  ['spi_5fexported_5ffunctions_5fgroup3_91',['SPI_Exported_Functions_Group3',['../group___s_p_i___exported___functions___group3.html',1,'']]],
  ['spiex_92',['SPIEx',['../group___s_p_i_ex.html',1,'']]],
  ['spiex_5fexported_5ffunctions_93',['SPIEx_Exported_Functions',['../group___s_p_i_ex___exported___functions.html',1,'']]],
  ['spiex_5fexported_5ffunctions_5fgroup1_94',['SPIEx_Exported_Functions_Group1',['../group___s_p_i_ex___exported___functions___group1.html',1,'']]],
  ['spline_20interpolation_95',['Cubic Spline Interpolation',['../group___spline_interpolate.html',1,'']]],
  ['square_20error_96',['Mean Square Error',['../group___m_s_e.html',1,'']]],
  ['square_20lms_20filters_97',['Least Mean Square (LMS) Filters',['../group___l_m_s.html',1,'']]],
  ['square_20rms_98',['Root mean square (RMS)',['../group___r_m_s.html',1,'']]],
  ['square_20root_99',['Square Root',['../group___s_q_r_t.html',1,'']]],
  ['squared_100',['Complex Magnitude Squared',['../group__cmplx__mag__squared.html',1,'']]],
  ['sram2_20erase_20on_20reset_20type_101',['FLASH Option Bytes User SRAM2 Erase On Reset Type',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m2___r_s_t.html',1,'']]],
  ['sram2_20page_20write_20protection_200_20to_2031_102',['SRAM2 Page Write protection (0 to 31)',['../group___s_y_s_c_f_g___s_r_a_m2_w_r_p.html',1,'']]],
  ['sram2_20parity_20check_20type_103',['FLASH Option Bytes User SRAM2 Parity Check Type',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m2___p_e.html',1,'']]],
  ['sram2_20retention_20in_20standby_20mode_104',['PWR SRAM2 Retention in Standby mode',['../group___p_w_r_ex___s_r_a_m2___retention.html',1,'']]],
  ['standard_20deviation_105',['Standard deviation',['../group___s_t_d.html',1,'']]],
  ['standby_106',['Standby',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_a_n_d_b_y.html',1,'FLASH Option Bytes User IWDG Mode On Standby'],['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_a_n_d_b_y.html',1,'FLASH Option Bytes User Reset On Standby']]],
  ['standby_20mode_107',['PWR SRAM2 Retention in Standby mode',['../group___p_w_r_ex___s_r_a_m2___retention.html',1,'']]],
  ['standby_20shutdown_20mode_108',['GPIO bit number for I/O setting in standby/shutdown mode',['../group___p_w_r_ex___g_p_i_o___bit___number.html',1,'']]],
  ['start_20or_20stop_20mode_109',['I2C Start or Stop Mode',['../group___i2_c___s_t_a_r_t___s_t_o_p___m_o_d_e.html',1,'']]],
  ['state_110',['State',['../group___channel___c_c___state.html',1,'TIM Capture/Compare Channel State'],['../group___t_i_m___output___compare___n___idle___state.html',1,'TIM Complementary Output Compare Idle State'],['../group___t_i_m___output___compare___n___state.html',1,'TIM Complementary Output Compare State'],['../group___t_i_m___output___compare___idle___state.html',1,'TIM Output Compare Idle State'],['../group___t_i_m___output___compare___state.html',1,'TIM Output Compare State'],['../group___t_i_m___output___fast___state.html',1,'TIM Output Fast State'],['../group___u_a_r_t___state.html',1,'UART State']]],
  ['state_111',['state',['../group___t_i_m___o_s_s_i___off___state___selection__for___idle__mode__state.html',1,'TIM OSSI OffState Selection for Idle mode state'],['../group___t_i_m___o_s_s_r___off___state___selection__for___run__mode__state.html',1,'TIM OSSR OffState Selection for Run mode state']]],
  ['state_20and_20error_20functions_112',['Peripheral State and Error functions',['../group___u_a_r_t___exported___functions___group4.html',1,'']]],
  ['state_20code_20definition_113',['UART State Code Definition',['../group___u_a_r_t___state___definition.html',1,'']]],
  ['state_20functions_114',['State functions',['../group___t_i_m_ex___exported___functions___group7.html',1,'Extended Peripheral State functions'],['../group___t_i_m___exported___functions___group10.html',1,'TIM Peripheral State functions']]],
  ['state_20mode_20and_20error_20functions_115',['Peripheral State, Mode and Error functions',['../group___i2_c___exported___functions___group3.html',1,'']]],
  ['state_20structure_20definition_116',['HAL state structure definition',['../group___h_a_l__state__structure__definition.html',1,'']]],
  ['states_117',['ADC States',['../group___a_d_c___states.html',1,'']]],
  ['statistics_20functions_118',['Statistics Functions',['../group__group_stats.html',1,'']]],
  ['status_119',['Status',['../group___r_c_c___a_h_b1___peripheral___clock___enable___disable___status.html',1,'AHB1 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b1___clock___sleep___enable___disable___status.html',1,'AHB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_h_b2___clock___enable___disable___status.html',1,'AHB2 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b2___clock___sleep___enable___disable___status.html',1,'AHB2 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_h_b3___clock___enable___disable___status.html',1,'AHB3 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b3___clock___sleep___enable___disable___status.html',1,'AHB3 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b1___clock___enable___disable___status.html',1,'APB1 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_p_b1___clock___sleep___enable___disable___status.html',1,'APB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b2___clock___enable___disable___status.html',1,'APB2 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_p_b2___clock___sleep___enable___disable___status.html',1,'APB2 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___system___clock___source___status.html',1,'System Clock Source Status']]],
  ['status_20and_20control_20registers_120',['Status and Control Registers',['../group___c_m_s_i_s___c_o_r_e.html',1,'']]],
  ['status_20flags_121',['Status Flags',['../group___p_w_r_ex___flag.html',1,'PWR Status Flags'],['../group___u_a_r_t___flags.html',1,'UART Status Flags']]],
  ['status_20level_122',['Status Level',['../group___s_p_i__reception__fifo__status__level.html',1,'SPI Reception FIFO Status Level'],['../group___s_p_i__transmission__fifo__status__level.html',1,'SPI Transmission FIFO Status Level']]],
  ['stm32l476xx_123',['Stm32l476xx',['../group__stm32l476xx.html',1,'']]],
  ['stm32l4xx_124',['Stm32l4xx',['../group__stm32l4xx.html',1,'']]],
  ['stm32l4xx_5fhal_5fdriver_125',['STM32L4xx_HAL_Driver',['../group___s_t_m32_l4xx___h_a_l___driver.html',1,'']]],
  ['stm32l4xx_5fll_5fdriver_126',['STM32L4xx_LL_Driver',['../group___s_t_m32_l4xx___l_l___driver.html',1,'']]],
  ['stm32l4xx_5fsystem_127',['Stm32l4xx_system',['../group__stm32l4xx__system.html',1,'']]],
  ['stm32l4xx_5fsystem_5fexported_5fconstants_128',['STM32L4xx_System_Exported_Constants',['../group___s_t_m32_l4xx___system___exported___constants.html',1,'']]],
  ['stm32l4xx_5fsystem_5fexported_5ffunctions_129',['STM32L4xx_System_Exported_Functions',['../group___s_t_m32_l4xx___system___exported___functions.html',1,'']]],
  ['stm32l4xx_5fsystem_5fexported_5fmacros_130',['STM32L4xx_System_Exported_Macros',['../group___s_t_m32_l4xx___system___exported___macros.html',1,'']]],
  ['stm32l4xx_5fsystem_5fexported_5fvariables_131',['STM32L4xx_System_Exported_Variables',['../group___s_t_m32_l4xx___system___exported___variables.html',1,'']]],
  ['stm32l4xx_5fsystem_5fincludes_132',['STM32L4xx_System_Includes',['../group___s_t_m32_l4xx___system___includes.html',1,'']]],
  ['stm32l4xx_5fsystem_5fprivate_5fdefines_133',['STM32L4xx_System_Private_Defines',['../group___s_t_m32_l4xx___system___private___defines.html',1,'']]],
  ['stm32l4xx_5fsystem_5fprivate_5ffunctionprototypes_134',['STM32L4xx_System_Private_FunctionPrototypes',['../group___s_t_m32_l4xx___system___private___function_prototypes.html',1,'']]],
  ['stm32l4xx_5fsystem_5fprivate_5ffunctions_135',['STM32L4xx_System_Private_Functions',['../group___s_t_m32_l4xx___system___private___functions.html',1,'']]],
  ['stm32l4xx_5fsystem_5fprivate_5fincludes_136',['STM32L4xx_System_Private_Includes',['../group___s_t_m32_l4xx___system___private___includes.html',1,'']]],
  ['stm32l4xx_5fsystem_5fprivate_5fmacros_137',['STM32L4xx_System_Private_Macros',['../group___s_t_m32_l4xx___system___private___macros.html',1,'']]],
  ['stm32l4xx_5fsystem_5fprivate_5ftypesdefinitions_138',['STM32L4xx_System_Private_TypesDefinitions',['../group___s_t_m32_l4xx___system___private___types_definitions.html',1,'']]],
  ['stm32l4xx_5fsystem_5fprivate_5fvariables_139',['STM32L4xx_System_Private_Variables',['../group___s_t_m32_l4xx___system___private___variables.html',1,'']]],
  ['stop_140',['Stop',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_o_p.html',1,'FLASH Option Bytes User IWDG Mode On Stop'],['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_o_p.html',1,'FLASH Option Bytes User Reset On Stop']]],
  ['stop_20bits_141',['UART Number of Stop Bits',['../group___u_a_r_t___stop___bits.html',1,'']]],
  ['stop_20clock_142',['Wake-Up from STOP Clock',['../group___r_c_c___stop___wake_up_clock.html',1,'']]],
  ['stop_20mode_143',['I2C Start or Stop Mode',['../group___i2_c___s_t_a_r_t___s_t_o_p___m_o_d_e.html',1,'']]],
  ['stop_20mode_20enable_144',['UART Advanced Feature Stop Mode Enable',['../group___u_a_r_t___stop___mode___enable.html',1,'']]],
  ['stop_20mode_20entry_145',['PWR STOP mode entry',['../group___p_w_r___s_t_o_p__mode__entry.html',1,'']]],
  ['stop_20selection_146',['UART WakeUp From Stop Selection',['../group___u_a_r_t___wake_up__from___stop___selection.html',1,'']]],
  ['stretch_20mode_147',['I2C No-Stretch Mode',['../group___i2_c___n_o_s_t_r_e_t_c_h___m_o_d_e.html',1,'']]],
  ['structure_148',['Structure',['../group___biquad_cascade_d_f2_t.html',1,'Biquad Cascade IIR Filters Using a Direct Form II Transposed Structure'],['../group___biquad_cascade_d_f1.html',1,'Biquad Cascade IIR Filters Using Direct Form I Structure']]],
  ['structure_20definition_149',['Structure definition',['../group___i2_c___configuration___structure__definition.html',1,'I2C Configuration Structure definition'],['../group___i2_c__handle___structure__definition.html',1,'I2C handle Structure definition']]],
  ['structure_20definition_150',['structure definition',['../group___h_a_l__mode__structure__definition.html',1,'HAL mode structure definition'],['../group___h_a_l__state__structure__definition.html',1,'HAL state structure definition']]],
  ['structures_151',['UTILS Exported structures',['../group___u_t_i_l_s___l_l___e_s___i_n_i_t.html',1,'']]],
  ['sub_20fields_152',['ADCx CFGR sub fields',['../group___a_d_c___c_f_g_r__fields__2.html',1,'']]],
  ['subtraction_153',['Subtraction',['../group___matrix_sub.html',1,'Matrix Subtraction'],['../group___basic_sub.html',1,'Vector Subtraction']]],
  ['support_20functions_154',['Support Functions',['../group__group_support.html',1,'']]],
  ['svm_155',['SVM',['../group__linearsvm.html',1,'Linear SVM'],['../group__polysvm.html',1,'Polynomial SVM'],['../group__rbfsvm.html',1,'RBF SVM'],['../group__sigmoidsvm.html',1,'Sigmoid SVM']]],
  ['svm_20functions_156',['SVM Functions',['../group__group_s_v_m.html',1,'']]],
  ['swap_157',['UART Advanced Feature RX TX Pins Swap',['../group___u_a_r_t___rx___tx___swap.html',1,'']]],
  ['syscfg_20aliased_20defines_20maintained_20for_20legacy_20purpose_158',['HAL SYSCFG Aliased Defines maintained for legacy purpose',['../group___h_a_l___s_y_s_c_f_g___aliased___defines.html',1,'']]],
  ['syscfg_20exported_20constants_159',['SYSCFG Exported Constants',['../group___s_y_s_c_f_g___exported___constants.html',1,'']]],
  ['syscfg_20exported_20macros_160',['SYSCFG Exported Macros',['../group___s_y_s_c_f_g___exported___macros.html',1,'']]],
  ['syscfg_20private_20macros_161',['SYSCFG Private Macros',['../group___s_y_s_c_f_g___private___macros.html',1,'']]],
  ['system_162',['SYSTEM',['../group___u_t_i_l_s___e_f___s_y_s_t_e_m.html',1,'']]],
  ['system_163',['TIM Break System',['../group___t_i_m___break___system.html',1,'']]],
  ['system_20clock_20source_164',['System Clock Source',['../group___r_c_c___system___clock___source.html',1,'']]],
  ['system_20clock_20source_20status_165',['System Clock Source Status',['../group___r_c_c___system___clock___source___status.html',1,'']]],
  ['system_20clock_20type_166',['System Clock Type',['../group___r_c_c___system___clock___type.html',1,'']]],
  ['system_20control_20block_20scb_167',['System Control Block (SCB)',['../group___c_m_s_i_s___s_c_b.html',1,'']]],
  ['system_20controls_20not_20in_20scb_20scnscb_168',['System Controls not in SCB (SCnSCB)',['../group___c_m_s_i_s___s_cn_s_c_b.html',1,'']]],
  ['system_20tick_20timer_20systick_169',['System Tick Timer (SysTick)',['../group___c_m_s_i_s___sys_tick.html',1,'']]],
  ['systick_170',['SYSTICK',['../group___c_o_r_t_e_x___l_l___e_f___s_y_s_t_i_c_k.html',1,'']]],
  ['systick_171',['System Tick Timer (SysTick)',['../group___c_m_s_i_s___sys_tick.html',1,'']]],
  ['systick_20clock_20source_172',['SYSTICK Clock Source',['../group___c_o_r_t_e_x___l_l___e_c___c_l_k_s_o_u_r_c_e___h_c_l_k.html',1,'']]],
  ['systick_20clock_20source_173',['CORTEX SysTick clock source',['../group___c_o_r_t_e_x___sys_tick__clock__source.html',1,'']]],
  ['systick_20functions_174',['SysTick Functions',['../group___c_m_s_i_s___core___sys_tick_functions.html',1,'']]]
];
