var searchData=
[
  ['backup_20domain_20reset_0',['RCC Backup Domain Reset',['../group___r_c_c___backup___domain___reset.html',1,'']]],
  ['banks_1',['FLASH Banks',['../group___f_l_a_s_h___banks.html',1,'']]],
  ['bartlett_20window_20function_2026_205_20db_2',['Bartlett window function (26.5 dB)',['../group___window_b_a_r_t_l_e_t_t.html',1,'']]],
  ['base_20address_3',['TIM DMA Base Address',['../group___t_i_m___d_m_a___base__address.html',1,'']]],
  ['base_20functions_4',['TIM Time Base functions',['../group___t_i_m___exported___functions___group1.html',1,'']]],
  ['based_20communications_20time_20out_20value_5',['UART polling-based communications time-out value',['../group___u_a_r_t___time_out___value.html',1,'']]],
  ['basic_20math_20functions_6',['Basic Math Functions',['../group__group_math.html',1,'']]],
  ['battery_20charging_7',['PWR battery charging',['../group___p_w_r_ex___v_b_a_t___battery___charging.html',1,'']]],
  ['battery_20charging_20resistor_20selection_8',['PWR battery charging resistor selection',['../group___p_w_r_ex___v_b_a_t___battery___charging___selection.html',1,'']]],
  ['baudrate_20enable_9',['UART Advanced Feature Auto BaudRate Enable',['../group___u_a_r_t___auto_baud_rate___enable.html',1,'']]],
  ['baudrate_20prescaler_10',['SPI BaudRate Prescaler',['../group___s_p_i___baud_rate___prescaler.html',1,'']]],
  ['bayesian_20estimators_11',['Bayesian estimators',['../group__group_bayes.html',1,'']]],
  ['behavior_20on_20conversion_20data_12',['ADC group regular - Overrun behavior on conversion data',['../group___a_d_c___h_a_l___e_c___r_e_g___o_v_r___d_a_t_a___b_e_h_a_v_i_o_r.html',1,'']]],
  ['bilinear_20interpolation_13',['Bilinear Interpolation',['../group___bilinear_interpolate.html',1,'']]],
  ['binary_20data_20inversion_14',['UART Advanced Feature Binary Data Inversion',['../group___u_a_r_t___data___inv.html',1,'']]],
  ['biquad_20cascade_20filter_15',['High Precision Q31 Biquad Cascade Filter',['../group___biquad_cascade_d_f1__32x64.html',1,'']]],
  ['biquad_20cascade_20iir_20filters_20using_20a_20direct_20form_20ii_20transposed_20structure_16',['Biquad Cascade IIR Filters Using a Direct Form II Transposed Structure',['../group___biquad_cascade_d_f2_t.html',1,'']]],
  ['biquad_20cascade_20iir_20filters_20using_20direct_20form_20i_20structure_17',['Biquad Cascade IIR Filters Using Direct Form I Structure',['../group___biquad_cascade_d_f1.html',1,'']]],
  ['bit_20field_20macros_18',['Core register bit field macros',['../group___c_m_s_i_s__core__bitfield.html',1,'']]],
  ['bit_20fixed_20point_20value_19',['bit fixed point value',['../group__q15__to__x.html',1,'Convert 16-bit fixed point value'],['../group__q31__to__x.html',1,'Convert 32-bit fixed point value'],['../group__q7__to__x.html',1,'Convert 8-bit fixed point value']]],
  ['bit_20floating_20point_20value_20',['Convert 32-bit floating point value',['../group__float__to__x.html',1,'']]],
  ['bit_20number_20for_20i_20o_20setting_20in_20standby_20shutdown_20mode_21',['GPIO bit number for I/O setting in standby/shutdown mode',['../group___p_w_r_ex___g_p_i_o___bit___number.html',1,'']]],
  ['bit_20sampling_20method_22',['UART One Bit Sampling Method',['../group___u_a_r_t___one_bit___sampling.html',1,'']]],
  ['bits_23',['UART Number of Stop Bits',['../group___u_a_r_t___stop___bits.html',1,'']]],
  ['bitwise_20and_24',['Vector bitwise AND',['../group___and.html',1,'']]],
  ['bitwise_20exclusive_20or_25',['Vector bitwise exclusive OR',['../group___xor.html',1,'']]],
  ['bitwise_20inclusive_20or_26',['Vector bitwise inclusive OR',['../group___or.html',1,'']]],
  ['bitwise_20not_27',['Vector bitwise NOT',['../group___not.html',1,'']]],
  ['blackman_20harris_20window_20function_2092_20db_28',['Blackman Harris window function (92 dB)',['../group___window_b_l_a_c_k_m_a_n___h_a_r_r_i_s__92_d_b.html',1,'']]],
  ['block_20scb_29',['System Control Block (SCB)',['../group___c_m_s_i_s___s_c_b.html',1,'']]],
  ['boolean_20distances_30',['Boolean Distances',['../group___bool_dist.html',1,'']]],
  ['boot_20mode_31',['Boot Mode',['../group___s_y_s_c_f_g___boot_mode.html',1,'']]],
  ['boot1_20type_32',['FLASH Option Bytes User BOOT1 Type',['../group___f_l_a_s_h___o_b___u_s_e_r__n_b_o_o_t1.html',1,'']]],
  ['bor_20level_33',['FLASH Option Bytes User BOR Level',['../group___f_l_a_s_h___o_b___u_s_e_r___b_o_r___l_e_v_e_l.html',1,'']]],
  ['braycurtis_34',['Braycurtis',['../group__braycurtis.html',1,'']]],
  ['break_20detection_35',['UART LIN Break Detection',['../group___u_a_r_t___l_i_n___break___detection.html',1,'']]],
  ['break_20input_36',['TIM Extended Break input',['../group___t_i_m_ex___break___input.html',1,'']]],
  ['break_20input_202_20enable_37',['TIM Break input 2 Enable',['../group___t_i_m___break2___input__enable__disable.html',1,'']]],
  ['break_20input_202_20polarity_38',['TIM Break Input 2 Polarity',['../group___t_i_m___break2___polarity.html',1,'']]],
  ['break_20input_20enable_39',['TIM Break Input Enable',['../group___t_i_m___break___input__enable__disable.html',1,'']]],
  ['break_20input_20polarity_40',['TIM Break Input Polarity',['../group___t_i_m___break___polarity.html',1,'']]],
  ['break_20input_20polarity_41',['TIM Extended Break input polarity',['../group___t_i_m_ex___break___input___source___polarity.html',1,'']]],
  ['break_20input_20source_42',['TIM Extended Break input source',['../group___t_i_m_ex___break___input___source.html',1,'']]],
  ['break_20input_20source_20enabling_43',['TIM Extended Break input source enabling',['../group___t_i_m_ex___break___input___source___enable.html',1,'']]],
  ['break_20system_44',['TIM Break System',['../group___t_i_m___break___system.html',1,'']]],
  ['burst_20length_45',['TIM DMA Burst Length',['../group___t_i_m___d_m_a___burst___length.html',1,'']]],
  ['by_20complex_20multiplication_46',['Complex-by-Complex Multiplication',['../group___cmplx_by_cmplx_mult.html',1,'']]],
  ['by_20real_20multiplication_47',['Complex-by-Real Multiplication',['../group___cmplx_by_real_mult.html',1,'']]],
  ['bypass_20activation_48',['HSE Bypass activation',['../group___u_t_i_l_s___e_c___h_s_e___b_y_p_a_s_s.html',1,'']]],
  ['bytes_20pcrop_20on_20rdp_20level_20type_49',['FLASH Option Bytes PCROP On RDP Level Type',['../group___f_l_a_s_h___o_b___p_c_r_o_p___r_d_p.html',1,'']]],
  ['bytes_20read_20protection_50',['FLASH Option Bytes Read Protection',['../group___f_l_a_s_h___o_b___read___protection.html',1,'']]],
  ['bytes_20type_51',['FLASH Option Bytes Type',['../group___f_l_a_s_h___o_b___type.html',1,'']]],
  ['bytes_20user_20boot1_20type_52',['FLASH Option Bytes User BOOT1 Type',['../group___f_l_a_s_h___o_b___u_s_e_r__n_b_o_o_t1.html',1,'']]],
  ['bytes_20user_20bor_20level_53',['FLASH Option Bytes User BOR Level',['../group___f_l_a_s_h___o_b___u_s_e_r___b_o_r___l_e_v_e_l.html',1,'']]],
  ['bytes_20user_20iwdg_20mode_20on_20standby_54',['FLASH Option Bytes User IWDG Mode On Standby',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_a_n_d_b_y.html',1,'']]],
  ['bytes_20user_20iwdg_20mode_20on_20stop_55',['FLASH Option Bytes User IWDG Mode On Stop',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_o_p.html',1,'']]],
  ['bytes_20user_20iwdg_20type_56',['FLASH Option Bytes User IWDG Type',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_w.html',1,'']]],
  ['bytes_20user_20reset_20on_20shutdown_57',['FLASH Option Bytes User Reset On Shutdown',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_h_u_t_d_o_w_n.html',1,'']]],
  ['bytes_20user_20reset_20on_20standby_58',['FLASH Option Bytes User Reset On Standby',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_a_n_d_b_y.html',1,'']]],
  ['bytes_20user_20reset_20on_20stop_59',['FLASH Option Bytes User Reset On Stop',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_o_p.html',1,'']]],
  ['bytes_20user_20sram2_20erase_20on_20reset_20type_60',['FLASH Option Bytes User SRAM2 Erase On Reset Type',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m2___r_s_t.html',1,'']]],
  ['bytes_20user_20sram2_20parity_20check_20type_61',['FLASH Option Bytes User SRAM2 Parity Check Type',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m2___p_e.html',1,'']]],
  ['bytes_20user_20type_62',['FLASH Option Bytes User Type',['../group___f_l_a_s_h___o_b___u_s_e_r___type.html',1,'']]],
  ['bytes_20user_20wwdg_20type_63',['FLASH Option Bytes User WWDG Type',['../group___f_l_a_s_h___o_b___u_s_e_r___w_w_d_g___s_w.html',1,'']]]
];
