var searchData=
[
  ['range_0',['MSI Clock Range',['../group___r_c_c___m_s_i___clock___range.html',1,'']]],
  ['ranks_1',['ranks',['../group___a_d_c___i_n_j___s_e_q___r_a_n_k_s.html',1,'ADC group injected - Sequencer ranks'],['../group___a_d_c___h_a_l___e_c___r_e_g___s_e_q___r_a_n_k_s.html',1,'ADC group regular - Sequencer ranks']]],
  ['rate_20mode_2',['UART Advanced Feature AutoBaud Rate Mode',['../group___u_a_r_t___auto_baud___rate___mode.html',1,'']]],
  ['ratio_3',['Oversampling - Ratio',['../group___a_d_c___h_a_l___e_c___o_v_s___r_a_t_i_o.html',1,'']]],
  ['rbf_20svm_4',['RBF SVM',['../group__rbfsvm.html',1,'']]],
  ['rcc_5',['RCC',['../group___r_c_c.html',1,'']]],
  ['rcc_20aliased_20maintained_20for_20legacy_20purpose_6',['HAL RCC Aliased maintained for legacy purpose',['../group___h_a_l___r_c_c___aliased.html',1,'']]],
  ['rcc_20backup_20domain_20reset_7',['RCC Backup Domain Reset',['../group___r_c_c___backup___domain___reset.html',1,'']]],
  ['rcc_20exported_20constants_8',['RCC Exported Constants',['../group___r_c_c___exported___constants.html',1,'']]],
  ['rcc_20exported_20macros_9',['RCC Exported Macros',['../group___r_c_c___exported___macros.html',1,'']]],
  ['rcc_20exported_20types_10',['RCC Exported Types',['../group___r_c_c___exported___types.html',1,'']]],
  ['rcc_20lse_20css_20external_20interrupt_20line_11',['RCC LSE CSS external interrupt line',['../group___r_c_c_ex___e_x_t_i___l_i_n_e___l_s_e_c_s_s.html',1,'']]],
  ['rcc_20private_20constants_12',['RCC Private Constants',['../group___r_c_c___private___constants.html',1,'']]],
  ['rcc_20rtc_20clock_20configuration_13',['RCC RTC Clock Configuration',['../group___r_c_c___r_t_c___clock___configuration.html',1,'']]],
  ['rcc_5fexported_5ffunctions_14',['RCC_Exported_Functions',['../group___r_c_c___exported___functions.html',1,'']]],
  ['rcc_5fexported_5ffunctions_5fgroup1_15',['RCC_Exported_Functions_Group1',['../group___r_c_c___exported___functions___group1.html',1,'']]],
  ['rcc_5fexported_5ffunctions_5fgroup2_16',['RCC_Exported_Functions_Group2',['../group___r_c_c___exported___functions___group2.html',1,'']]],
  ['rcc_5fprivate_5fmacros_17',['RCC_Private_Macros',['../group___r_c_c___private___macros.html',1,'']]],
  ['rccex_18',['RCCEx',['../group___r_c_c_ex.html',1,'']]],
  ['rccex_20exported_20constants_19',['RCCEx Exported Constants',['../group___r_c_c_ex___exported___constants.html',1,'']]],
  ['rccex_20exported_20macros_20',['RCCEx Exported Macros',['../group___r_c_c_ex___exported___macros.html',1,'']]],
  ['rccex_20exported_20types_21',['RCCEx Exported Types',['../group___r_c_c_ex___exported___types.html',1,'']]],
  ['rccex_5fexported_5ffunctions_22',['RCCEx_Exported_Functions',['../group___r_c_c_ex___exported___functions.html',1,'']]],
  ['rccex_5fexported_5ffunctions_5fgroup1_23',['RCCEx_Exported_Functions_Group1',['../group___r_c_c_ex___exported___functions___group1.html',1,'']]],
  ['rccex_5fexported_5ffunctions_5fgroup2_24',['RCCEx_Exported_Functions_Group2',['../group___r_c_c_ex___exported___functions___group2.html',1,'']]],
  ['rccex_5fprivate_5fconstants_25',['RCCEx_Private_Constants',['../group___r_c_c_ex___private___constants.html',1,'']]],
  ['rccex_5fprivate_5fmacros_26',['RCCEx_Private_Macros',['../group___r_c_c_ex___private___macros.html',1,'']]],
  ['rdp_20level_20type_27',['FLASH Option Bytes PCROP On RDP Level Type',['../group___f_l_a_s_h___o_b___p_c_r_o_p___r_d_p.html',1,'']]],
  ['read_20protection_28',['FLASH Option Bytes Read Protection',['../group___f_l_a_s_h___o_b___read___protection.html',1,'']]],
  ['real_20fft_20f32_20functions_29',['Real FFT F32 Functions',['../group___real_f_f_t_f32.html',1,'']]],
  ['real_20fft_20f64_20functions_30',['Real FFT F64 Functions',['../group___real_f_f_t_f64.html',1,'']]],
  ['real_20fft_20functions_31',['Real FFT Functions',['../group___deprecated_real_f_f_t.html',1,'Deprecated Real FFT Functions'],['../group___real_f_f_t.html',1,'Real FFT Functions']]],
  ['real_20fft_20q15_20functions_32',['Real FFT Q15 Functions',['../group___real_f_f_t_q15.html',1,'']]],
  ['real_20fft_20q31_20functions_33',['Real FFT Q31 Functions',['../group___real_f_f_t_q31.html',1,'']]],
  ['real_20fft_20tables_34',['Real FFT Tables',['../group___real_f_f_t___table.html',1,'']]],
  ['real_20multiplication_35',['Complex-by-Real Multiplication',['../group___cmplx_by_real_mult.html',1,'']]],
  ['receiver_20timeout_36',['UART Receiver Timeout',['../group___u_a_r_t___receiver___timeout.html',1,'']]],
  ['reception_20fifo_20status_20level_37',['SPI Reception FIFO Status Level',['../group___s_p_i__reception__fifo__status__level.html',1,'']]],
  ['reception_20threshold_38',['SPI FIFO Reception Threshold',['../group___s_p_i___f_i_f_o__reception__threshold.html',1,'']]],
  ['reception_20type_20values_39',['UART Reception type values',['../group___u_a_r_t___reception___type___values.html',1,'']]],
  ['reference_40',['Functions and Instructions Reference',['../group___c_m_s_i_s___core___function_interface.html',1,'']]],
  ['register_41',['Register',['../group___u_a_r_t___c_r2___a_d_d_r_e_s_s___l_s_b___p_o_s.html',1,'UART Address-matching LSB Position In CR2 Register'],['../group___u_a_r_t___c_r1___d_e_a_t___a_d_d_r_e_s_s___l_s_b___p_o_s.html',1,'UART Driver Enable Assertion Time LSB Position In CR1 Register'],['../group___u_a_r_t___c_r1___d_e_d_t___a_d_d_r_e_s_s___l_s_b___p_o_s.html',1,'UART Driver Enable DeAssertion Time LSB Position In CR1 Register']]],
  ['register_20access_20functions_42',['CMSIS Core Register Access Functions',['../group___c_m_s_i_s___core___reg_acc_functions.html',1,'']]],
  ['register_20bit_20field_20macros_43',['Core register bit field macros',['../group___c_m_s_i_s__core__bitfield.html',1,'']]],
  ['registers_44',['Status and Control Registers',['../group___c_m_s_i_s___c_o_r_e.html',1,'']]],
  ['registers_20coredebug_45',['Core Debug Registers (CoreDebug)',['../group___c_m_s_i_s___core_debug.html',1,'']]],
  ['regular_46',['Oversampling - Oversampling scope for ADC group regular',['../group___a_d_c___h_a_l___e_c___o_v_s___s_c_o_p_e___r_e_g.html',1,'']]],
  ['regular_20overrun_20behavior_20on_20conversion_20data_47',['ADC group regular - Overrun behavior on conversion data',['../group___a_d_c___h_a_l___e_c___r_e_g___o_v_r___d_a_t_a___b_e_h_a_v_i_o_r.html',1,'']]],
  ['regular_20sequencer_20ranks_48',['ADC group regular - Sequencer ranks',['../group___a_d_c___h_a_l___e_c___r_e_g___s_e_q___r_a_n_k_s.html',1,'']]],
  ['regular_20trigger_20edge_20when_20external_20trigger_20is_20selected_49',['ADC group regular trigger edge (when external trigger is selected)',['../group___a_d_c__regular__external__trigger__edge.html',1,'']]],
  ['regular_20trigger_20source_50',['ADC group regular trigger source',['../group___a_d_c__regular__external__trigger__source.html',1,'']]],
  ['regular_20window_20functions_51',['Regular window functions',['../group___window_normal.html',1,'']]],
  ['regulator_20mode_52',['PWR regulator mode',['../group___p_w_r___regulator__state__in___s_l_e_e_p___s_t_o_p__mode.html',1,'']]],
  ['regulator_20voltage_20scale_53',['PWR Regulator voltage scale',['../group___p_w_r_ex___regulator___voltage___scale.html',1,'']]],
  ['release_20reset_54',['Release Reset',['../group___r_c_c___a_h_b1___force___release___reset.html',1,'AHB1 Peripheral Force Release Reset'],['../group___r_c_c___a_h_b2___force___release___reset.html',1,'AHB2 Peripheral Force Release Reset'],['../group___r_c_c___a_h_b3___force___release___reset.html',1,'AHB3 Peripheral Force Release Reset'],['../group___r_c_c___a_p_b1___force___release___reset.html',1,'APB1 Peripheral Force Release Reset'],['../group___r_c_c___a_p_b2___force___release___reset.html',1,'APB2 Peripheral Force Release Reset']]],
  ['reload_20end_20mode_55',['I2C Reload End Mode',['../group___i2_c___r_e_l_o_a_d___e_n_d___m_o_d_e.html',1,'']]],
  ['reload_20preload_56',['TIM Auto-Reload Preload',['../group___t_i_m___auto_reload_preload.html',1,'']]],
  ['remap_57',['TIM Update Interrupt Flag Remap',['../group___t_i_m___update___interrupt___flag___remap.html',1,'']]],
  ['remapping_58',['TIM Extended Remapping',['../group___t_i_m_ex___remap.html',1,'']]],
  ['request_59',['DMA request',['../group___d_m_a__request.html',1,'']]],
  ['request_20parameters_60',['UART Request Parameters',['../group___u_a_r_t___request___parameters.html',1,'']]],
  ['request_20selection_61',['CCx DMA request selection',['../group___t_i_m___c_c___d_m_a___request.html',1,'']]],
  ['reset_62',['Reset',['../group___r_c_c___a_h_b1___force___release___reset.html',1,'AHB1 Peripheral Force Release Reset'],['../group___r_c_c___a_h_b2___force___release___reset.html',1,'AHB2 Peripheral Force Release Reset'],['../group___r_c_c___a_h_b3___force___release___reset.html',1,'AHB3 Peripheral Force Release Reset'],['../group___r_c_c___a_p_b1___force___release___reset.html',1,'APB1 Peripheral Force Release Reset'],['../group___r_c_c___a_p_b2___force___release___reset.html',1,'APB2 Peripheral Force Release Reset'],['../group___r_c_c___backup___domain___reset.html',1,'RCC Backup Domain Reset']]],
  ['reset_20flag_63',['Reset Flag',['../group___r_c_c___reset___flag.html',1,'']]],
  ['reset_20on_20shutdown_64',['FLASH Option Bytes User Reset On Shutdown',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_h_u_t_d_o_w_n.html',1,'']]],
  ['reset_20on_20standby_65',['FLASH Option Bytes User Reset On Standby',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_a_n_d_b_y.html',1,'']]],
  ['reset_20on_20stop_66',['FLASH Option Bytes User Reset On Stop',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_o_p.html',1,'']]],
  ['reset_20type_67',['FLASH Option Bytes User SRAM2 Erase On Reset Type',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m2___r_s_t.html',1,'']]],
  ['resistor_20selection_68',['PWR battery charging resistor selection',['../group___p_w_r_ex___v_b_a_t___battery___charging___selection.html',1,'']]],
  ['resolution_69',['ADC instance - Resolution',['../group___a_d_c___h_a_l___e_c___r_e_s_o_l_u_t_i_o_n.html',1,'']]],
  ['response_20fir_20decimator_70',['Finite Impulse Response (FIR) Decimator',['../group___f_i_r__decimate.html',1,'']]],
  ['response_20fir_20filters_71',['Finite Impulse Response (FIR) Filters',['../group___f_i_r.html',1,'']]],
  ['response_20fir_20interpolator_72',['Finite Impulse Response (FIR) Interpolator',['../group___f_i_r___interpolate.html',1,'']]],
  ['response_20fir_20lattice_20filters_73',['Finite Impulse Response (FIR) Lattice Filters',['../group___f_i_r___lattice.html',1,'']]],
  ['response_20fir_20sparse_20filters_74',['Finite Impulse Response (FIR) Sparse Filters',['../group___f_i_r___sparse.html',1,'']]],
  ['response_20iir_20lattice_20filters_75',['Infinite Impulse Response (IIR) Lattice Filters',['../group___i_i_r___lattice.html',1,'']]],
  ['retention_20in_20standby_20mode_76',['PWR SRAM2 Retention in Standby mode',['../group___p_w_r_ex___s_r_a_m2___retention.html',1,'']]],
  ['retrieve_20polarity_20information_20from_20pwr_5fwakeup_5fpiny_5fxxx_20constants_77',['Shift to apply to retrieve polarity information from PWR_WAKEUP_PINy_xxx constants',['../group___p_w_r_ex___w_u_p___polarity.html',1,'']]],
  ['rms_78',['Root mean square (RMS)',['../group___r_m_s.html',1,'']]],
  ['rng_20aliased_20macros_20maintained_20for_20legacy_20purpose_79',['HAL RNG Aliased Macros maintained for legacy purpose',['../group___h_a_l___r_n_g___aliased___macros.html',1,'']]],
  ['rng_20clock_20source_80',['RNG Clock Source',['../group___r_c_c_ex___r_n_g___clock___source.html',1,'']]],
  ['root_81',['Square Root',['../group___s_q_r_t.html',1,'']]],
  ['root_20mean_20square_20rms_82',['Root mean square (RMS)',['../group___r_m_s.html',1,'']]],
  ['rotation_83',['Quaternion to Rotation',['../group___quat_rot.html',1,'']]],
  ['rotation_20to_20quaternion_84',['Rotation to Quaternion',['../group___rot_quat.html',1,'']]],
  ['rtc_20aliased_20defines_20maintained_20for_20legacy_20purpose_85',['HAL RTC Aliased Defines maintained for legacy purpose',['../group___h_a_l___r_t_c___aliased___defines.html',1,'']]],
  ['rtc_20aliased_20functions_20maintained_20for_20legacy_20purpose_86',['HAL RTC Aliased Functions maintained for legacy purpose',['../group___h_a_l___r_t_c___aliased___functions.html',1,'']]],
  ['rtc_20aliased_20macros_20maintained_20for_20legacy_20purpose_87',['HAL RTC Aliased Macros maintained for legacy purpose',['../group___h_a_l___r_t_c___aliased___macros.html',1,'']]],
  ['rtc_20clock_20configuration_88',['RCC RTC Clock Configuration',['../group___r_c_c___r_t_c___clock___configuration.html',1,'']]],
  ['rtc_20clock_20source_89',['RTC Clock Source',['../group___r_c_c___r_t_c___clock___source.html',1,'']]],
  ['run_20mode_20state_90',['TIM OSSR OffState Selection for Run mode state',['../group___t_i_m___o_s_s_r___off___state___selection__for___run__mode__state.html',1,'']]],
  ['rx_91',['UART DMA Rx',['../group___u_a_r_t___d_m_a___rx.html',1,'']]],
  ['rx_20error_92',['UART Advanced Feature DMA Disable On Rx Error',['../group___u_a_r_t___d_m_a___disable__on___rx___error.html',1,'']]],
  ['rx_20pin_20active_20level_20inversion_93',['UART Advanced Feature RX Pin Active Level Inversion',['../group___u_a_r_t___rx___inv.html',1,'']]],
  ['rx_20tx_20pins_20swap_94',['UART Advanced Feature RX TX Pins Swap',['../group___u_a_r_t___rx___tx___swap.html',1,'']]],
  ['rxevent_20type_20values_95',['UART RxEvent type values',['../group___u_a_r_t___rx_event___type___values.html',1,'']]]
];
