var dir_28bbf2235498980d5f928087bd3c4284 =
[
    [ "arm_atan2_f16.c", "arm__atan2__f16_8c_source.html", null ],
    [ "arm_atan2_f32.c", "arm__atan2__f32_8c_source.html", null ],
    [ "arm_atan2_q15.c", "arm__atan2__q15_8c_source.html", null ],
    [ "arm_atan2_q31.c", "arm__atan2__q31_8c_source.html", null ],
    [ "arm_cos_f32.c", "arm__cos__f32_8c_source.html", null ],
    [ "arm_cos_q15.c", "arm__cos__q15_8c_source.html", null ],
    [ "arm_cos_q31.c", "arm__cos__q31_8c_source.html", null ],
    [ "arm_divide_q15.c", "arm__divide__q15_8c_source.html", null ],
    [ "arm_divide_q31.c", "arm__divide__q31_8c_source.html", null ],
    [ "arm_sin_f32.c", "arm__sin__f32_8c_source.html", null ],
    [ "arm_sin_q15.c", "arm__sin__q15_8c_source.html", null ],
    [ "arm_sin_q31.c", "arm__sin__q31_8c_source.html", null ],
    [ "arm_sqrt_q15.c", "arm__sqrt__q15_8c_source.html", null ],
    [ "arm_sqrt_q31.c", "arm__sqrt__q31_8c_source.html", null ],
    [ "arm_vexp_f16.c", "arm__vexp__f16_8c_source.html", null ],
    [ "arm_vexp_f32.c", "arm__vexp__f32_8c_source.html", null ],
    [ "arm_vexp_f64.c", "arm__vexp__f64_8c_source.html", null ],
    [ "arm_vinverse_f16.c", "arm__vinverse__f16_8c_source.html", null ],
    [ "arm_vlog_f16.c", "arm__vlog__f16_8c_source.html", null ],
    [ "arm_vlog_f32.c", "arm__vlog__f32_8c_source.html", null ],
    [ "arm_vlog_f64.c", "arm__vlog__f64_8c_source.html", null ],
    [ "arm_vlog_q15.c", "arm__vlog__q15_8c_source.html", null ],
    [ "arm_vlog_q31.c", "arm__vlog__q31_8c_source.html", null ]
];